export const citroenyears =
{
    "resultCount": 72,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "18CI001",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Berlingo Multispace BlueHDi 100 Feel",
            "nybilspris": "189900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI002",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Berlingo Multispace PureTech 110 Feel",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI003",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 68 Live",
            "nybilspris": "99900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI004",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 68 S&S Feel",
            "nybilspris": "104900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI005",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 68 S&S Shine",
            "nybilspris": "119900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI041",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 72 Live",
            "nybilspris": "104900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI042",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 72 S&S Feel",
            "nybilspris": "109900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI043",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 72 S&S Shine",
            "nybilspris": "124900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI006",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross BlueHDi 100 Feel",
            "nybilspris": "204900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI007",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross BlueHDi 100 Shine",
            "nybilspris": "234800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI008",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 110 S&S Feel",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI009",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 110 S&S Shine",
            "nybilspris": "214800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI010",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 82 Feel",
            "nybilspris": "169800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI011",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 82 Live",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI012",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 BlueHDi 100 S&S Feel",
            "nybilspris": "169800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI013",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 BlueHDi 100 S&S Live",
            "nybilspris": "162900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI014",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 BlueHDi 100 S&S Shine",
            "nybilspris": "189700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI015",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 110 S&S Feel",
            "nybilspris": "149800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI016",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 110 S&S Live",
            "nybilspris": "142900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI017",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 110 S&S Shine",
            "nybilspris": "169700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI044",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Elle",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI018",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Feel",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI019",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Feel Free",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI020",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Live",
            "nybilspris": "127900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI021",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Shine",
            "nybilspris": "154700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI045",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus BlueHDi 100 Feel",
            "nybilspris": "179900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI046",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus BlueHDi 100 Shine",
            "nybilspris": "189900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI047",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus PureTech 110 S&S Feel",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI048",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus PureTech 110 S&S Live",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI049",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus PureTech 110 S&S Shine",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI022",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso / C4 SpaceTourer BlueHDi 120 S&S Feel",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI023",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso /C4 SpaceTourer BlueHDi 120 S&S Live",
            "nybilspris": "219900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI024",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso / C4 SpaceTourer BlueHDi 120 S&S Shine",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI025",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso /C4 SpaceTourer BlueHDi 150 EAT6 Shine",
            "nybilspris": "289900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI026",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso / C4 SpaceTourer PureTech 130 S&S Feel",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI027",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso / C4 SpaceTourer PureTech 130 S&S Live",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI028",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Picasso / C4 SpaceTourer PureTech 130 S&S Shine",
            "nybilspris": "244900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI067",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer BlueHDi 130 S&S Feel",
            "nybilspris": "249900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI068",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer BlueHDi 130 S&S Shine",
            "nybilspris": "274900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI069",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer BlueHDi 160 S&S EAT8 Shine",
            "nybilspris": "309900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI050",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  BlueHDi 120 S&S Feel",
            "nybilspris": "244900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI051",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  BlueHDi 120 S&S Live",
            "nybilspris": "244900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI052",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  BlueHDi 120 S&S Shine",
            "nybilspris": "269900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI053",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  BlueHDi 150 S&S EAT6 Shine",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI054",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  PureTech 130 S&S Feel",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI055",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  PureTech 130 S&S Live",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI056",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso / Grand C4 SpaceTourer  PureTech 130 S&S Shine",
            "nybilspris": "254900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI029",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso BlueHDi 120 S&S Feel",
            "nybilspris": "249900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI030",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso BlueHDi 120 S&S Live",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI031",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso BlueHDi 120 S&S Shine",
            "nybilspris": "274900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI032",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso BlueHDi 150 EAT6 Shine",
            "nybilspris": "304900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI033",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso PureTech 130 S&S Feel",
            "nybilspris": "234900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI034",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso PureTech 130 S&S Live",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI035",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Picasso PureTech 130 S&S Shine",
            "nybilspris": "259900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI070",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer  BlueHDi 130 S&S Feel",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI071",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer  BlueHDi 130 S&S Shine",
            "nybilspris": "284900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI072",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer  BlueHDi 160 S&S EAT8 Shine",
            "nybilspris": "319900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI057",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 100 S&S Feel",
            "nybilspris": "239900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI058",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 100 S&S Shine",
            "nybilspris": "259800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI059",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "269900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI060",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 130 S&S EAT8 Shine",
            "nybilspris": "289800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI061",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M PureTech 110 S&S Feel",
            "nybilspris": "229800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI062",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M PureTech 110 S&S Live",
            "nybilspris": "209900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI063",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M PureTech 110 S&S Shine",
            "nybilspris": "249700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI064",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo XL BlueHDi 100 Feel",
            "nybilspris": "257900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI065",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo XL BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI066",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo XL PureTech 110 S&S Feel",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI036",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer M BlueHDi 150 S&S",
            "nybilspris": "459900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI037",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer M BlueHDi 180 S&S EAT6",
            "nybilspris": "489900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI038",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer M BlueHDi 180 S&S EAT6 Launch Edition",
            "nybilspris": "489900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI039",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer XL BlueHDi 150 S&S",
            "nybilspris": "474900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18CI040",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer XL BlueHDi 180 S&S EAT6",
            "nybilspris": "504900",
            "bransletyp": "Diesel",
            "justering": ""
        },

        {
            "fordonstyp": "Personbil",
            "kod": "19CI001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 72 Live",
            "nybilspris": "119900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 72 S&S Feel",
            "nybilspris": "124900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 VTi 72 S&S Shine",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross BlueHDi 100 Feel",
            "nybilspris": "209900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross BlueHDi 100 Shine",
            "nybilspris": "239800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 110 S&S Feel",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 110 S&S Shine",
            "nybilspris": "224800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 82 Feel",
            "nybilspris": "184800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross PureTech 82 Live",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 110 S&S Feel",
            "nybilspris": "154800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 110 S&S Shine",
            "nybilspris": "174700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Feel",
            "nybilspris": "139800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Live",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 PureTech 82 Shine",
            "nybilspris": "159700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus BlueHDi 100 Feel",
            "nybilspris": "179900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus BlueHDi 100 Feel",
            "nybilspris": "199900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus BlueHDi 100 Shine",
            "nybilspris": "189900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus BlueHDi 100 Shine",
            "nybilspris": "209900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus PureTech 110 S&S Feel",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus PureTech 110 S&S Live",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus PureTech 110 S&S Shine",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "274900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer BlueHDi 130 S&S EAT8 Shine",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer BlueHDi 160 S&S EAT8 Shine",
            "nybilspris": "319900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer PureTech 130 S&S Feel",
            "nybilspris": "244900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer PureTech 130 S&S Live",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 SpaceTourer PureTech 130 S&S Shine",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C5 Aircross BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "329900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C5 Aircross BlueHDi 180 S&S EAT8 Shine",
            "nybilspris": "369900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C5 Aircross PureTech 180 S&S EAT8 Feel",
            "nybilspris": "309900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C5 Aircross PureTech 180 S&S EAT8 Shine",
            "nybilspris": "329900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "284900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer BlueHDi 130 S&S EAT8 Shine",
            "nybilspris": "309900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer BlueHDi 160 S&S EAT8 Shine",
            "nybilspris": "329900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer PureTech 130 S&S Feel",
            "nybilspris": "254900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer PureTech 130 S&S Live",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer PureTech 130 S&S Shine",
            "nybilspris": "279900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer PureTech 180 S&S EAT8 Feel",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 SpaceTourer PureTech 180 S&S EAT8 Shine",
            "nybilspris": "314900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 100 S&S Feel",
            "nybilspris": "239900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 100 S&S Shine",
            "nybilspris": "259800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "269900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M BlueHDi 130 S&S EAT8 Shine",
            "nybilspris": "289800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M PureTech 110 S&S Feel",
            "nybilspris": "229800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M PureTech 110 S&S Live",
            "nybilspris": "209900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo M PureTech 110 S&S Shine",
            "nybilspris": "249700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo XL BlueHDi 100 Feel",
            "nybilspris": "257900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo XL BlueHDi 130 S&S EAT8 Feel",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Nya Berlingo XL PureTech 110 S&S Feel",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer M BlueHDi 150 S&S",
            "nybilspris": "459900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer M BlueHDi 180 S&S EAT8",
            "nybilspris": "489900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer XL BlueHDi 150 S&S",
            "nybilspris": "474900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19CI045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "SpaceTourer XL BlueHDi 180 S&S EAT8",
            "nybilspris": "504900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI001",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Berlingo M 110 S&S",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI002",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C1 Vti 72 S&S Live",
            "nybilspris": "124900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI003",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross Puretech 110 S&S Feel",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI004",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Aircross Puretech 82 Live",
            "nybilspris": "194800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI005",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Puretech 110 S&S Feel",
            "nybilspris": "174800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI006",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C3 Puretech 82 S&S Live",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI007",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Cactus Puretech 110 S&S Live",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI008",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C4 Spacetourer Puretech 130 S&S Live",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI009",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "C5 Aircross Puretech 180 S&S EAT8",
            "nybilspris": "339900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20CI010",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Citroën",
            "modell": "Grand C4 Spacetourer 130 S&S Live",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}