export const hondayears =
{
    "resultCount": 56,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "18HO001",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,5 COMFORT",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO002",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,5 ELEGANCE NAVI",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO003",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,5 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO042",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,6 COMFORT",
            "nybilspris": "216900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO043",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,6 ELEGANCE NAVI",
            "nybilspris": "236900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO044",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,6 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "261900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO004",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 COMFORT",
            "nybilspris": "196900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO005",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 ELEGANCE NAVI",
            "nybilspris": "216900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO006",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 EXECUTIVE NAVI",
            "nybilspris": "241900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO007",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "256900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO045",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 S",
            "nybilspris": "185900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO008",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,5 PRESTIGE NAVI",
            "nybilspris": "266900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO009",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,5 SPORT NAVI",
            "nybilspris": "236900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO010",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,5 SPORT PLUS NAVI",
            "nybilspris": "256900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO046",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 COMFORT",
            "nybilspris": "211900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO047",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 ELEGANCE NAVI",
            "nybilspris": "232900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO048",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 EXECUTIVE NAVI",
            "nybilspris": "257900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO049",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "272900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO011",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC Type R 2,0 BASE",
            "nybilspris": "341900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO012",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC Type R 2,0 GT",
            "nybilspris": "379900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO050",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 ELEGANCE NAVI",
            "nybilspris": "309500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO051",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 EXECUTIVE NAVI",
            "nybilspris": "377500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO052",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 LIFESTYLE NAVI",
            "nybilspris": "342500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO053",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 LIFESTYLE NAVI 7 Seats",
            "nybilspris": "359500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO054",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,5 COMFORT",
            "nybilspris": "260900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO055",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,5 ELEGANCE NAVI",
            "nybilspris": "294500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO013",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,6 Comfort",
            "nybilspris": "259000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO014",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,6 Elegance Plus NAVI",
            "nybilspris": "286000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO015",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,6 Lifestyle Plus NAVI",
            "nybilspris": "300000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO016",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 2,0 Comfort",
            "nybilspris": "239000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO017",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 2,0 Elegance Plus NAVI",
            "nybilspris": "267000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO018",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1,6 Elegance Plus NAVI",
            "nybilspris": "322000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO019",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1,6 Executive NAVI",
            "nybilspris": "375000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO020",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1,6 Executive NAVI SENSING",
            "nybilspris": "393000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO021",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1,6 Lifestyle Plus NAVI",
            "nybilspris": "336000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO022",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 2,0 Comfort",
            "nybilspris": "262000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO023",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 2,0 Elegance Plus NAVI",
            "nybilspris": "289000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO024",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 2,0 Executive NAVI",
            "nybilspris": "342000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO025",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 2,0 Executive NAVI SENSING",
            "nybilspris": "360000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO026",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 2,0 Lifestyle Plus NAVI",
            "nybilspris": "314000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO027",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 COMFORT",
            "nybilspris": "194500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO028",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 ELEGANCE ADAS",
            "nybilspris": "214500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO029",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 ELEGANCE ADAS NAVI",
            "nybilspris": "224500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO030",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 EXECUTIVE ADAS",
            "nybilspris": "242500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO056",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 EXECUTIVE NAVI",
            "nybilspris": "247500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO031",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,6 COMFORT",
            "nybilspris": "219500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO032",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,6 ELEGANCE ADAS",
            "nybilspris": "239500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO033",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,6 ELEGANCE ADAS NAVI",
            "nybilspris": "249500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO034",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,6 EXECUTIVE ADAS",
            "nybilspris": "267500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO035",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 COMFORT",
            "nybilspris": "164500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO036",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 COMFORT NAVI",
            "nybilspris": "174500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO037",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 ELEGANCE",
            "nybilspris": "187500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO038",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 ELEGANCE NAVI",
            "nybilspris": "197500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO039",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 TREND",
            "nybilspris": "154500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO040",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,5 DYNAMIC",
            "nybilspris": "187500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18HO041",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,5 DYNAMIC NAVI",
            "nybilspris": "197500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,5 COMFORT",
            "nybilspris": "223900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,5 ELEGANCE NAVI",
            "nybilspris": "245500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,5 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "270500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,6 COMFORT",
            "nybilspris": "216900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,6 ELEGANCE NAVI",
            "nybilspris": "236900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 4D 1,6 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "261900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 COMFORT",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 DYNAMIC NAVI",
            "nybilspris": "234200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 ELEGANCE NAVI",
            "nybilspris": "221900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 EXECUTIVE NAVI",
            "nybilspris": "246900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "261900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,0 S",
            "nybilspris": "185900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,5 PRESTIGE NAVI",
            "nybilspris": "274900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,5 SPORT NAVI",
            "nybilspris": "244500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,5 SPORT PLUS NAVI",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 COMFORT",
            "nybilspris": "211900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 ELEGANCE NAVI",
            "nybilspris": "232900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 EXECUTIVE NAVI",
            "nybilspris": "257900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CIVIC 5D 1,6 EXECUTIVE PREMIUM NAVI",
            "nybilspris": "272900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 ELEGANCE NAVI",
            "nybilspris": "309500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 EXECUTIVE NAVI",
            "nybilspris": "377500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 LIFESTYLE NAVI",
            "nybilspris": "342500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 1,5 LIFESTYLE NAVI 7 Seats",
            "nybilspris": "359500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HO019",
            "marke": "Honda",
            "modell": "CR-V 2,0 ELEGANCE NAVI CVT, miljöbil",
            "nybilspris": "371900",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HO020",
            "marke": "Honda",
            "modell": "CR-V 2,0 EXECUTIVE NAVI CVT, miljöbil",
            "nybilspris": "444900",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HO021",
            "marke": "Honda",
            "modell": "CR-V 2,0 LIFESTYLE NAVI CVT, miljöbil",
            "nybilspris": "407900",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,5 COMFORT",
            "nybilspris": "260900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1,5 ELEGANCE NAVI",
            "nybilspris": "294500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HO026",
            "marke": "Honda",
            "modell": "CR-V 2WD 2,0 COMFORT CVT, miljöbil",
            "nybilspris": "325900",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HO027",
            "marke": "Honda",
            "modell": "CR-V 2WD 2,0 ELEGANCE NAVI CVT, miljöbil",
            "nybilspris": "350900",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HO027",
            "marke": "Honda",
            "modell": "CR-V 2WD 2,0 LIFESTYLE NAVI CVT, miljöbil",
            "nybilspris": "386900",
            "bransletyp": "Elhybrid",
            "justering": "59000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 COMFORT",
            "nybilspris": "195500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 ELEGANCE NAVI",
            "nybilspris": "225500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5 EXECUTIVE NAVI",
            "nybilspris": "247500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1,5T SPORT NAVI",
            "nybilspris": "276500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 COMFORT",
            "nybilspris": "168200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 COMFORT NAVI",
            "nybilspris": "178200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 ELEGANCE",
            "nybilspris": "191200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 ELEGANCE NAVI",
            "nybilspris": "201200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,3 TREND",
            "nybilspris": "158200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,5 DYNAMIC",
            "nybilspris": "191200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "JAZZ 1,5 DYNAMIC NAVI",
            "nybilspris": "201200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "TYPE R 2,0 BASE",
            "nybilspris": "350500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HO042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "TYPE R 2,0 GT",
            "nybilspris": "389500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO001",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "Civic 4D 1.5 Elegance Navi",
            "nybilspris": "255400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO002",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "Civic 4D 1.5 Executive Premium Navi",
            "nybilspris": "281400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO003",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1.5 Comfort",
            "nybilspris": "268800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO004",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 2WD 1.5 Elegance Navi",
            "nybilspris": "302800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO005",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO003",
            "marke": "Honda",
            "modell": "CR-V 2WD 2.0 Comfort, miljöbil",
            "nybilspris": "335700",
            "bransletyp": "Elhybrid",
            "justering": "32000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO006",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO004",
            "marke": "Honda",
            "modell": "CR-V 2WD 2.0 Elegance Navi, miljöbil",
            "nybilspris": "361700",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO007",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO010",
            "marke": "Honda",
            "modell": "CR-V 2WD 2.0 Lifestyle Navi, miljöbil",
            "nybilspris": "398700",
            "bransletyp": "Elhybrid",
            "justering": "5000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO008",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1.5 Elegance Navi",
            "nybilspris": "318800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO009",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1.5 Executive Navi",
            "nybilspris": "388800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO010",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1.5 Lifestyle Navi",
            "nybilspris": "352800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO011",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "CR-V 4WD 1.5 Lifestyle Navi 7 seats",
            "nybilspris": "369800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO012",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO008",
            "marke": "Honda",
            "modell": "CR-V 4WD 2.0 Elegance Navi, miljöbil",
            "nybilspris": "383700",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO013",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO009",
            "marke": "Honda",
            "modell": "CR-V 4WD 2.0 Executive Navi, miljöbil",
            "nybilspris": "458700",
            "bransletyp": "Elhybrid",
            "justering": "20000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO014",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO010",
            "marke": "Honda",
            "modell": "CR-V 4WD 2.0 Lifestyle Navi, miljöbil",
            "nybilspris": "420700",
            "bransletyp": "Elhybrid",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO015",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20HO015",
            "marke": "Honda",
            "modell": "Honda e, miljöbil",
            "nybilspris": "370200",
            "bransletyp": "El",
            "justering": "-151800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO016",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1.5 Comfort",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO017",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1.5 Elegance Navi",
            "nybilspris": "232000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO018",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1.5 Executive Navi",
            "nybilspris": "254000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO019",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "HR-V 1.5T Sport Navi",
            "nybilspris": "285000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO020",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "Jazz 1.3 Comfort",
            "nybilspris": "172900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO021",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "Jazz 1.3 Elegance Navi",
            "nybilspris": "206900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20HO022",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Honda",
            "modell": "Jazz 1.3 Trend",
            "nybilspris": "162900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}