export const kiayears = {
    "resultCount": 67,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "18KI001",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Carens 1.6 Advance",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI002",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Carens 1.7 CRDi 115hk Advance",
            "nybilspris": "203800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI003",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd 1.4 Special Edition",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI004",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd 1.6 Advance",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI005",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd 1.6 CRDi ECO Advance",
            "nybilspris": "180900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI006",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd 1.6 CRDi GT-Line",
            "nybilspris": "183800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI007",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd Sportswagon 1.6 Advance",
            "nybilspris": "173900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI008",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd Sportswagon 1.6 CRDi Advance",
            "nybilspris": "189900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI009",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd Sportswagon 1.6 CRDi GT-Line",
            "nybilspris": "192800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI044",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "cee'd Sportswagon 1.6 GDi GT-Line",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI056",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.0 T-GDi Action",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI057",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.4 T-GDi Advance",
            "nybilspris": "196400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI058",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.4 T-GDi Advance DCT7",
            "nybilspris": "211400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI059",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.0 T-GDi Advance",
            "nybilspris": "190300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI060",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi Advance",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI061",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi Advance DCT7",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI012",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI004",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid DCT6 Advance, miljöbil",
            "nybilspris": "214900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI010",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI004",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid DCT6 Advance PlusPaket 1, miljöbil",
            "nybilspris": "234800",
            "bransletyp": "Elhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI011",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI004",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid DCT6 Advance PlusPaket 2, miljöbil",
            "nybilspris": "254700",
            "bransletyp": "Elhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI015",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI004",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance, miljöbil",
            "nybilspris": "298900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI013",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI004",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance PlusPaket 1, miljöbil",
            "nybilspris": "318800",
            "bransletyp": "Laddhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI014",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI004",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "338700",
            "bransletyp": "Laddhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI016",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 1,7 CRDi DCT7 GT Line",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI017",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 1,7 CRDi DCT7 GT Line Plus",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI062",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 1.6 CRDi DCT7 GT Line",
            "nybilspris": "319000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI063",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 1.6 T-GDi DCT7 GT Line",
            "nybilspris": "319000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI018",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 2,0 T GDi AUT GT",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI019",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 2.0 AUT Advance",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI020",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI019",
            "marke": "KIA",
            "modell": "Optima Sportswagon Plug-in Hybrid Advance Plus, miljöbil",
            "nybilspris": "404900",
            "bransletyp": "Laddhybrid",
            "justering": "25000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI021",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI019",
            "marke": "KIA",
            "modell": "Optima Sportswagon Plug-in Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "424800",
            "bransletyp": "Laddhybrid",
            "justering": "44900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI045",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1,0 T-GDI GT Line",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI022",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.0 Advance",
            "nybilspris": "114900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI064",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.0 T-GDi 100 hk GT Line",
            "nybilspris": "134900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI023",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.2 AUT Advance",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI046",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1,0 T-GDI GT Line",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI066",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.0 T-GDi 120hk DCT7 Advance",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI065",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.0 T-GDi 120 hk GT Line",
            "nybilspris": "168900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI024",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.2 Advance",
            "nybilspris": "135900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI025",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.4 AUT Advance",
            "nybilspris": "152900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI026",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT Advance",
            "nybilspris": "364900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI047",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT GT Line",
            "nybilspris": "419900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI067",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT GT Line 7-sits",
            "nybilspris": "426900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI027",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT Special Edition",
            "nybilspris": "399900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI028",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Soul 1.6 Advance",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI029",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Soul 1.6 CRDi Advance",
            "nybilspris": "184900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI030",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Soul 1.6 T-GDI DCT7",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI031",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18KI029",
            "marke": "KIA",
            "modell": "Soul EV, miljöbil",
            "nybilspris": "316600",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI032",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1,6 2WD Advance",
            "nybilspris": "227800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI051",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1,6-T 2WD Advance",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI033",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1,6-T DCT7 AWD GT-Line",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI034",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1,7 CRDi 2WD Advance",
            "nybilspris": "239900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI068",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 CRDi 136 hk DCT7 AWD Advance",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI069",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 CRDi 136 hk DCT7 AWD GT Line",
            "nybilspris": "337900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI070",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 T-GDi 177 hk DCT7 AWD Advance",
            "nybilspris": "284900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI071",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 T-GDi DCT7 AWD GT Line",
            "nybilspris": "322900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI035",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 2,0 CRDi 184hk AWD GT-Line",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI072",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 2.0 CRDi MHEV AUT AWD GT Line",
            "nybilspris": "352900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI036",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 2.2 CRDi AWD AT8 GT Line",
            "nybilspris": "429900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI037",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 2.2 CRDi AWD AT8 GT Line Plus",
            "nybilspris": "453800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI038",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 3.3 T-GDi AWD AT8",
            "nybilspris": "514900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI073",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 100 hk Advance",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI039",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 120 hk Advance Plus",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI074",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 120 hk DCT7 Advance",
            "nybilspris": "192900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI040",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.2 Action",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI041",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.4 Advance",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI042",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Venga 1.4 CRDi Advance",
            "nybilspris": "165900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18KI043",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Venga 1.6 AUT Advance",
            "nybilspris": "167900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.0 T-GDi Action",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.0 T-GDi Advance",
            "nybilspris": "186800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.4 T-GDi Advance",
            "nybilspris": "196400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.0 T-GDi Advance",
            "nybilspris": "190300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi Advance",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi DCT Advance",
            "nybilspris": "226400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi DCT GT Line",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.6 CRDi GT Line",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "e-Niro Advance, miljöbil",
            "nybilspris": "429900",
            "bransletyp": "El",
            "justering": "29900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "e-Niro Advance Plus, miljöbil",
            "nybilspris": "459800",
            "bransletyp": "El",
            "justering": "49800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI027",
            "marke": "KIA",
            "modell": "e-Soul Advance,miljöbil",
            "nybilspris": "429900",
            "bransletyp": "El",
            "justering": "38000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI027",
            "marke": "KIA",
            "modell": "e-Soul Advance Plus,miljöbil",
            "nybilspris": "459800",
            "bransletyp": "El",
            "justering": "67900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance, miljöbil",
            "nybilspris": "220900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance PlusPaket 1, miljöbil",
            "nybilspris": "230800",
            "bransletyp": "Elhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance PlusPaket 1 (ny version), miljöbil",
            "nybilspris": "260800",
            "bransletyp": "Elhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "250700",
            "bransletyp": "Elhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance PlusPaket 2 (ny version), miljöbil",
            "nybilspris": "280700",
            "bransletyp": "Elhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance, miljöbil",
            "nybilspris": "304900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance PlusPaket 1, miljöbil",
            "nybilspris": "324800",
            "bransletyp": "Laddhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "344700",
            "bransletyp": "Laddhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 1.6 CRDi DCT GT Line",
            "nybilspris": "319000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 1.6 T-GDi DCT GT Line",
            "nybilspris": "319000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Optima Sportswagon 2.0 AUT Advance",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI018",
            "marke": "KIA",
            "modell": "Optima Sportswagon Plug-in Hybrid Advance Plus, miljöbil",
            "nybilspris": "412900",
            "bransletyp": "Laddhybrid",
            "justering": "25000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19KI018",
            "marke": "KIA",
            "modell": "Optima Sportswagon Plug-in Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "432800",
            "bransletyp": "Laddhybrid",
            "justering": "44900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.0 Advance",
            "nybilspris": "116900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.0 T-GDi 100 hk GT Line",
            "nybilspris": "135900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.2 AUT Advance",
            "nybilspris": "131900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "ProCeed 1.4 T-GDi DCT GT Line",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "ProCeed 1.6 T-GDi GT",
            "nybilspris": "295500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.0 T-GDi 120hk DCT Advance",
            "nybilspris": "170900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.0 T-GDi 120 hk GT Line",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.2 Advance",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT Advance 7-sits",
            "nybilspris": "374900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT GT Line 7-sits",
            "nybilspris": "399900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 CRDi 136 hk DCT AWD Advance",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 CRDi 136 hk DCT AWD GT Line",
            "nybilspris": "337900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 T-GDi 177 hk DCT AWD Advance",
            "nybilspris": "284900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 T-GDi DCT AWD GT Line",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 2.0 CRDi MHEV AUT AWD GT Line",
            "nybilspris": "352900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 2.2 CRDi AWD AT8 GT Line",
            "nybilspris": "445900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 2.2 CRDi AWD AT8 GT Line Plus",
            "nybilspris": "465800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 3.3 T-GDi AWD AT8",
            "nybilspris": "525900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 100 hk Advance",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 120 hk Advance Plus",
            "nybilspris": "188900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19KI041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 120 hk DCT Advance",
            "nybilspris": "192900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI001",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.0 T-GDi Action",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI002",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.0 T-GDi Advance",
            "nybilspris": "189300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI003",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed 1.4 T-GDi Advance",
            "nybilspris": "196400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI004",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.0 T-GDi Advance",
            "nybilspris": "192800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI005",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi Advance",
            "nybilspris": "202400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI006",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi DCT Advance",
            "nybilspris": "226400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI007",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.4 T-GDi DCT GT Line",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI008",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Ceed SW 1.6 CRDi GT Line",
            "nybilspris": "237400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI010",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "e-Niro Advance, miljöbil",
            "nybilspris": "481900",
            "bransletyp": "El",
            "justering": "29900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI009",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "e-Niro Advance Plus, miljöbil",
            "nybilspris": "506800",
            "bransletyp": "El",
            "justering": "49800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI012",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI027",
            "marke": "KIA",
            "modell": "e-Soul Advance, miljöbil",
            "nybilspris": "429900",
            "bransletyp": "El",
            "justering": "27000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI011",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI027",
            "marke": "KIA",
            "modell": "e-Soul Advance Plus, miljöbil",
            "nybilspris": "459800",
            "bransletyp": "El",
            "justering": "56900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI015",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance, miljöbil",
            "nybilspris": "255900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI013",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance PlusPaket 1, miljöbil",
            "nybilspris": "275800",
            "bransletyp": "Elhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI014",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "295700",
            "bransletyp": "Elhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI018",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance, miljöbil",
            "nybilspris": "334900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI016",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance PlusPaket 1, miljöbil",
            "nybilspris": "354800",
            "bransletyp": "Laddhybrid",
            "justering": "19900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI017",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI003",
            "marke": "KIA",
            "modell": "Niro 1.6 Plug-In Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "374700",
            "bransletyp": "Laddhybrid",
            "justering": "39800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI019",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI006",
            "marke": "KIA",
            "modell": "Optima Sportswagon Plug-in Hybrid Advance Plus, miljöbil",
            "nybilspris": "415700",
            "bransletyp": "Laddhybrid",
            "justering": "15300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI020",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20KI006",
            "marke": "KIA",
            "modell": "Optima Sportswagon Plug-in Hybrid Advance PlusPaket 2, miljöbil",
            "nybilspris": "435600",
            "bransletyp": "Laddhybrid",
            "justering": "38200"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI021",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.0 Advance",
            "nybilspris": "124900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI022",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.0 T-GDi 100 hk GT Line",
            "nybilspris": "148700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI023",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Picanto 1.2 AUT Advance",
            "nybilspris": "134400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI024",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "ProCeed 1.4 T-GDi DCT GT Line",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI025",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "ProCeed 1.6 T-GDi GT",
            "nybilspris": "295500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI027",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.0 T-GDi 120hk DCT Advance",
            "nybilspris": "184800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI026",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.0 T-GDi 120 hk GT Line",
            "nybilspris": "177900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI028",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Rio 1.2 Advance",
            "nybilspris": "144900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI029",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sorento 2.2 CRDi AWD AUT GT Line 7-sits",
            "nybilspris": "399900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI030",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 CRDi 136 hk DCT AWD Advance",
            "nybilspris": "302700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI031",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 CRDi 136 hk DCT AWD GT Line",
            "nybilspris": "340700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI032",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 T-GDi 177 hk DCT AWD Advance",
            "nybilspris": "287700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI033",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 1.6 T-GDi DCT AWD GT Line",
            "nybilspris": "325700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI034",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Sportage 2.0 CRDi MHEV AUT AWD GT Line",
            "nybilspris": "355700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI035",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stinger 3.3 T-GDi AWD AT8",
            "nybilspris": "528400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI036",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 100 hk Advance",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI037",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 120 hk Advance Plus",
            "nybilspris": "188900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20KI038",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "KIA",
            "modell": "Stonic 1.0 T-GDi 120 hk DCT Advance",
            "nybilspris": "192900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}