export const mazdayears = {
    "resultCount": 56,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "18MA022",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 115 hk Optimum",
            "nybilspris": "167900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA023",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 75 hk Core",
            "nybilspris": "131900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA024",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk Core",
            "nybilspris": "136900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA025",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk Vision",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA026",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk VisionRed",
            "nybilspris": "162900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA027",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 1.5 Core",
            "nybilspris": "167100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA028",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 1.5 DE Core",
            "nybilspris": "189100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA029",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 1.5 DE Vision",
            "nybilspris": "204100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA030",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Aut. Vision Business Edition",
            "nybilspris": "183900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA031",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Core",
            "nybilspris": "172100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA032",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Optimum",
            "nybilspris": "227500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA033",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Optimum Business Edition",
            "nybilspris": "207900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA034",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Vision",
            "nybilspris": "187100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA035",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 VisionPlus",
            "nybilspris": "202100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA036",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.2 DE Optimum",
            "nybilspris": "247500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA037",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.2 DE VisionPlus",
            "nybilspris": "219100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA038",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 1.5 DE Vision",
            "nybilspris": "204100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA039",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.0 Vision",
            "nybilspris": "187100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA040",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.2 DE Optimum",
            "nybilspris": "247500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA041",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.0 Core, Wagon",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA042",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.0 Vision, Sedan",
            "nybilspris": "261400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA043",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.0 Vision, Wagon",
            "nybilspris": "261400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA044",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE aut. Optimum, Wagon AWD",
            "nybilspris": "339300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA045",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE aut. Optimum, Wagon AWD, Business Edition",
            "nybilspris": "309900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA046",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE aut. VisionPlus, Wagon AWD",
            "nybilspris": "314300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA047",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Core, Wagon",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA048",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Optimum, Sedan",
            "nybilspris": "315900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA049",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Optimum, Wagon",
            "nybilspris": "315900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA050",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Vision, Sedan",
            "nybilspris": "281400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA051",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Vision, Wagon",
            "nybilspris": "281400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA052",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Vision, Wagon AWD",
            "nybilspris": "288300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA053",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.5 Optimum, Sedan",
            "nybilspris": "312400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA054",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.5 Optimum, Wagon",
            "nybilspris": "312400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA055",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.5 Optimum, Wagon, Business Edition",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA001",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 1.5 DE 105 hk, AWD, AUT, Optimum",
            "nybilspris": "251900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA056",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 1.8 DE 115 hk, AWD, AUT, Optimum",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA002",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 120 hk Core",
            "nybilspris": "173900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA003",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 120 hk Optimum",
            "nybilspris": "207900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA004",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 120 hk Vision",
            "nybilspris": "188400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA005",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 150 hk, AWD, AUT, Optimum",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA006",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 150 hk, AWD, AUT. Optimum, Business Edition",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA007",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.0 Core",
            "nybilspris": "244900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA008",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.0 Vision",
            "nybilspris": "259900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA009",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.0 VisionPlus AWD",
            "nybilspris": "282900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA010",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE AUT. Optimum, AWD, Business Edition",
            "nybilspris": "327500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA011",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE Optimum AWD",
            "nybilspris": "344900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA012",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE Vision",
            "nybilspris": "287900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA013",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE VisionPlus AWD",
            "nybilspris": "310900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA014",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.5 aut. Optimum AWD",
            "nybilspris": "331900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA015",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.5 aut. Optimum AWD, Business Edition",
            "nybilspris": "302900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA016",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 1.5",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA017",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 1.5 RF",
            "nybilspris": "248400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA018",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0",
            "nybilspris": "256000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA019",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0 RF",
            "nybilspris": "279500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA020",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0 Sport",
            "nybilspris": "272400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18MA021",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0 Sport RF",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 115 hk Optimum",
            "nybilspris": "171900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 75 hk Core",
            "nybilspris": "132900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk Core",
            "nybilspris": "137900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk Vision",
            "nybilspris": "150900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 1.5 Core",
            "nybilspris": "167100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 1.5 DE Core",
            "nybilspris": "189100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 1.5 DE Vision",
            "nybilspris": "204100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA060",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 (180 hk) Cosmo Business Edition, miljöbil",
            "nybilspris": "272900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA061",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 (180 hk) Sky med Tech Pack, miljöbil",
            "nybilspris": "280900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Aut. Vision Business Edition",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Core",
            "nybilspris": "172100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA051",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Cosmo, miljöbil",
            "nybilspris": "264900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Optimum",
            "nybilspris": "227500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Optimum Business Edition",
            "nybilspris": "207000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA052",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Sky, miljöbil",
            "nybilspris": "229900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 Vision",
            "nybilspris": "187100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 VisionPlus",
            "nybilspris": "202100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.2 DE Optimum",
            "nybilspris": "247500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 2.2 DE VisionPlus",
            "nybilspris": "219100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 1.5 DE Vision",
            "nybilspris": "204100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA062",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.0 (180 hk) Cosmo, miljöbil",
            "nybilspris": "299900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA064",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.0 (180 hk) Sky, miljöbil",
            "nybilspris": "264900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA063",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.0 (180 hk) Sky med Tech Pack, miljöbil",
            "nybilspris": "280900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.0 Vision",
            "nybilspris": "187100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda3 Sedan 2.2 DE Optimum",
            "nybilspris": "247500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.0 Vision, Sedan",
            "nybilspris": "270900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.0 Vision, Wagon",
            "nybilspris": "270900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE aut. Optimum, Wagon AWD",
            "nybilspris": "351900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE aut. Optimum, Wagon AWD, Business Edition",
            "nybilspris": "337900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Optimum, Sedan",
            "nybilspris": "344900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Optimum, Wagon",
            "nybilspris": "328400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Vision, Sedan",
            "nybilspris": "297900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Vision, Wagon",
            "nybilspris": "297900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.2 DE Vision, Wagon AWD",
            "nybilspris": "321400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.5 Optimum, Sedan",
            "nybilspris": "317900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.5 Optimum, Wagon",
            "nybilspris": "317900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 2.5 Optimum, Wagon, Business Edition",
            "nybilspris": "304900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA053",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (122 hk) Cosmo, miljöbil",
            "nybilspris": "284900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA055",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (122 hk) Sky, miljöbil",
            "nybilspris": "249900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA054",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (122 hk) Sky med Tech Pack, miljöbil",
            "nybilspris": "264900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA057",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (180 hk) Cosmo, miljöbil",
            "nybilspris": "315900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA056",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (180 hk) Cosmo Business Edition, miljöbil",
            "nybilspris": "287500",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA059",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (180 hk) Sky, miljöbil",
            "nybilspris": "279900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19MA058",
            "marke": "Mazda",
            "modell": "Mazda CX-30 2.0 (180 hk) Sky med Tech Pack, miljöbil",
            "nybilspris": "294900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 1.8 DE 115 hk, AWD, AUT, Optimum",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 121 hk Core",
            "nybilspris": "176900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 121 hk Optimum",
            "nybilspris": "212900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 121 hk Vision",
            "nybilspris": "192400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 150 hk, AWD, AUT, Optimum",
            "nybilspris": "244900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-3 2.0 150 hk, AWD, AUT. Optimum, Business Edition",
            "nybilspris": "222900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.0 Vision",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.0 VisionPlus AWD",
            "nybilspris": "294900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE AUT. Optimum, AWD, Business Edition",
            "nybilspris": "344500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE Optimum AWD",
            "nybilspris": "361900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE Vision",
            "nybilspris": "300900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.2 DE VisionPlus AWD",
            "nybilspris": "330900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.5 aut. Optimum AWD",
            "nybilspris": "341400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda CX-5 2.5 aut. Optimum AWD, Business Edition",
            "nybilspris": "310900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 1.5",
            "nybilspris": "246400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 1.5 RF",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0",
            "nybilspris": "266000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0 RF",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0 Sport",
            "nybilspris": "282400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19MA020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda MX-5 2.0 Sport RF",
            "nybilspris": "305900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA001",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA001",
            "marke": "Mazda",
            "modell": "CX-30 1.8D 116 hk, Aut, AWD, Cosmo, miljöbil",
            "nybilspris": "370800",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA002",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA002",
            "marke": "Mazda",
            "modell": "CX-30 1.8D 116 hk, Aut, Sky, miljöbil",
            "nybilspris": "315800",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA003",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA003",
            "marke": "Mazda",
            "modell": "CX-30 2.0 150 hk, Cosmo, miljöbil",
            "nybilspris": "309900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA005",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA005",
            "marke": "Mazda",
            "modell": "CX-30 2.0 150 hk, Sky, miljöbil",
            "nybilspris": "269900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA004",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA004",
            "marke": "Mazda",
            "modell": "CX-30 2.0 150 hk, Sky med Tech Pack, miljöbil",
            "nybilspris": "288900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA006",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA006",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, AWD, Cosmo, miljöbil",
            "nybilspris": "355900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA008",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA008",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, AWD, Sky, miljöbil",
            "nybilspris": "314900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA007",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA007",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, AWD, Sky med Tech Pack, miljöbil",
            "nybilspris": "333900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA010",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA010",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, Cosmo, miljöbil",
            "nybilspris": "330900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA009",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA009",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, Cosmo Business Edition, miljöbil",
            "nybilspris": "301400",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA012",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA012",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, Sky, miljöbil",
            "nybilspris": "289900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA011",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA011",
            "marke": "Mazda",
            "modell": "CX-30 2.0 180 hk, Sky med Tech Pack, miljöbil",
            "nybilspris": "308900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA013",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.0 165 hk, Aut, AWD, VisionPlus",
            "nybilspris": "341900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA014",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.0 165 hk, Vision",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA015",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.2 DE 150 hk, AWD, VisionPlus",
            "nybilspris": "377900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA016",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.2 DE 150 hk, Vision",
            "nybilspris": "335900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA017",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.2 DE 184 hk, Aut, AWD, Optimum Business Edition",
            "nybilspris": "360900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA018",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.2 DE 184 hk, AWD, Optimum",
            "nybilspris": "396400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA020",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.5, 194 hk, Aut, AWD, Optimum Business Edition",
            "nybilspris": "348400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA019",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "CX-5 2.5 194 hk, Aut, AWD, Optimum",
            "nybilspris": "382900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA021",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk, Core",
            "nybilspris": "184000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA022",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk, Optimum",
            "nybilspris": "235000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA023",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda2 1.5 90 hk, Vision",
            "nybilspris": "204000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA024",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA024",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 150 hk, Cosmo, miljöbil",
            "nybilspris": "299900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA026",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA026",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 150 hk, Sky, miljöbil",
            "nybilspris": "259900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA025",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA025",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 150 hk, Sky med Tech Pack, miljöbil",
            "nybilspris": "278900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA027",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA027",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 180 hk, AWD, Cosmo, miljöbil",
            "nybilspris": "344900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA029",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA029",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 180 hk, Cosmo, miljöbil",
            "nybilspris": "319900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA028",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA028",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 180 hk, Cosmo Business Edition, miljöbil",
            "nybilspris": "291400",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA031",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA031",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 180 hk, Sky, miljöbil",
            "nybilspris": "279900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA030",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20MA030",
            "marke": "Mazda",
            "modell": "Mazda3 2.0 180 hk, Sky med Tech Pack, miljöbil",
            "nybilspris": "299900",
            "bransletyp": "Elhybrid",
            "justering": "-14900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA032",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Sedan 2.0 165 hk, Aut, Vision",
            "nybilspris": "328400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA033",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Sedan 2.2 DE 150 hk, Aut, Vision",
            "nybilspris": "380400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA034",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Sedan 2.2 DE 184 hk, Aut, Optimum",
            "nybilspris": "410900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA035",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Sedan 2.5 194 hk, Aut, Optimum",
            "nybilspris": "387900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA036",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.0 165 hk, Aut, Vision",
            "nybilspris": "328400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA037",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.2 DE 150 hk, Aut, AWD, Vision",
            "nybilspris": "410400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA038",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.2 DE 150 hk, Aut, Vision",
            "nybilspris": "380400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA039",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.2 DE 184 hk, Aut, AWD, Optimum",
            "nybilspris": "437900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA040",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.2 DE 184 hk, Aut, AWD, Optimum Business Edition",
            "nybilspris": "398900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA041",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.2 DE 184 hk, Aut, Optimum",
            "nybilspris": "410900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA042",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.5 194 hk, Aut, Optimum",
            "nybilspris": "387900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA043",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "Mazda6 Wagon 2.5 194 hk, Aut, Optimum Business Edition",
            "nybilspris": "352900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA044",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "MX-5 1.5 132 hk",
            "nybilspris": "314900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA045",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "MX-5 2.0 184 hk",
            "nybilspris": "342900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA046",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "MX-5 RF 1.5 132 hk",
            "nybilspris": "338400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20MA047",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Mazda",
            "modell": "MX-5 RF 2.0 184 hk",
            "nybilspris": "366400",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}