export const porscheyears =
{
    "resultCount": 50,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "18PR001",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster",
            "nybilspris": "553000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR002",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster GTS",
            "nybilspris": "779000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR003",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster S",
            "nybilspris": "671000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR004",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman",
            "nybilspris": "532000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR005",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GTS",
            "nybilspris": "758000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR006",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman S",
            "nybilspris": "650000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR007",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera",
            "nybilspris": "942000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR008",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4",
            "nybilspris": "1010000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR009",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 Cabriolet",
            "nybilspris": "1131000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR010",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 GTS",
            "nybilspris": "1272000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR011",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 GTS Cabriolet",
            "nybilspris": "1393000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR012",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S",
            "nybilspris": "1144000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR013",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S Cabriolet",
            "nybilspris": "1265000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR014",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera Cabriolet",
            "nybilspris": "1063000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR015",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera GTS",
            "nybilspris": "1203000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR016",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera GTS Cabriolet",
            "nybilspris": "1324000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR017",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S",
            "nybilspris": "1075000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR018",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S Cabriolet",
            "nybilspris": "1196000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR019",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera T",
            "nybilspris": "1035000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR020",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 GT2 RS",
            "nybilspris": "2700000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR021",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 GT3",
            "nybilspris": "1515000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR022",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Targa 4",
            "nybilspris": "1131000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR023",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Targa 4 GTS",
            "nybilspris": "1393000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR024",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Targa 4S",
            "nybilspris": "1265000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR025",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Turbo",
            "nybilspris": "1681000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR026",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Turbo Cabriolet",
            "nybilspris": "1802000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR027",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Turbo S",
            "nybilspris": "1945000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR028",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Turbo S Cabriolet",
            "nybilspris": "2066000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR029",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Turbo S Exclusive Series",
            "nybilspris": "2465000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR030",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne",
            "nybilspris": "745000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR050",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18PR030",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid, miljöbil",
            "nybilspris": "915000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR031",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S",
            "nybilspris": "925000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR032",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo",
            "nybilspris": "1385000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR033",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan",
            "nybilspris": "576000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR034",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan GTS",
            "nybilspris": "755000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR035",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan S",
            "nybilspris": "636000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR036",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan S Diesel",
            "nybilspris": "636000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR037",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan Turbo",
            "nybilspris": "838000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR038",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan Turbo Performance Package",
            "nybilspris": "908000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR039",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera",
            "nybilspris": "825000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR040",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4",
            "nybilspris": "865000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR042",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18PR040",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid, miljöbil",
            "nybilspris": "1020000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR041",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18PR043",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1050000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR044",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S",
            "nybilspris": "1140000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR043",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4 Sport Turismo",
            "nybilspris": "895000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR045",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S Sport Turismo",
            "nybilspris": "1190000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR046",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo",
            "nybilspris": "1550000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR048",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18PR046",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1850000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR047",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18PR049",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1880000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18PR049",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo Sport Turismo",
            "nybilspris": "1580000",
            "bransletyp": "Bensin",
            "justering": ""
        },

        {
            "fordonstyp": "Personbil",
            "kod": "19PR001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster",
            "nybilspris": "570000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster GTS",
            "nybilspris": "790000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster S",
            "nybilspris": "693000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster T",
            "nybilspris": "660000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman",
            "nybilspris": "549000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GT4",
            "nybilspris": "965000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GTS",
            "nybilspris": "769000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman S",
            "nybilspris": "672000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman T",
            "nybilspris": "639000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Spyder",
            "nybilspris": "940000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera",
            "nybilspris": "1025000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4",
            "nybilspris": "1100000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 Cabriolet",
            "nybilspris": "1235000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 GTS",
            "nybilspris": "1312000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 GTS Cabriolet",
            "nybilspris": "1433000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S",
            "nybilspris": "1225000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S Cabriolet",
            "nybilspris": "1355000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera Cabriolet",
            "nybilspris": "1160000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera GTS",
            "nybilspris": "1203000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera GTS Cabriolet",
            "nybilspris": "1324000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S",
            "nybilspris": "1155000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S Cabriolet",
            "nybilspris": "1285000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 GT3 RS",
            "nybilspris": "1950000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Targa 4 GTS",
            "nybilspris": "1433000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne",
            "nybilspris": "745000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Coupé",
            "nybilspris": "830000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR011",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid, miljöbil",
            "nybilspris": "915000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR041",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid Coupé, miljöbil",
            "nybilspris": "979000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S",
            "nybilspris": "925000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S Coupé",
            "nybilspris": "995000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo",
            "nybilspris": "1385000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo Coupé",
            "nybilspris": "1464000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR014",
            "marke": "Porsche",
            "modell": "Cayenne Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1725000",
            "bransletyp": "Laddhybrid",
            "justering": "76700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR044",
            "marke": "Porsche",
            "modell": "Cayenne Turbo S E-Hybrid Coupé, miljöbil",
            "nybilspris": "1765000",
            "bransletyp": "Laddhybrid",
            "justering": "62200"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan",
            "nybilspris": "600000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan S",
            "nybilspris": "660000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan Turbo",
            "nybilspris": "910000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4",
            "nybilspris": "877000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR016",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid, miljöbil",
            "nybilspris": "1059000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR019",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1089000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S",
            "nybilspris": "1172000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4 Sport Turismo",
            "nybilspris": "907000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S Sport Turismo",
            "nybilspris": "1222000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera GTS",
            "nybilspris": "1375000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera GTS Sport Turismo",
            "nybilspris": "1405000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo",
            "nybilspris": "1569000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR025",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1870000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR025",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1900000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo Sport Turismo",
            "nybilspris": "1599000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR016",
            "marke": "Porsche",
            "modell": "Taycan Turbo, miljöbil",
            "nybilspris": "1700000",
            "bransletyp": "El",
            "justering": "151100"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR048",
            "marke": "Porsche",
            "modell": "Taycan  Turbo S, miljöbil",
            "nybilspris": "2080000",
            "bransletyp": "El",
            "justering": "281900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR001",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster",
            "nybilspris": "582000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR002",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster GTS",
            "nybilspris": "802000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR003",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster S",
            "nybilspris": "700000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR004",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster T",
            "nybilspris": "672000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR005",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman",
            "nybilspris": "560000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR006",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GT4",
            "nybilspris": "965000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR007",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GTS",
            "nybilspris": "780000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR008",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman S",
            "nybilspris": "678000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR009",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman T",
            "nybilspris": "650000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR010",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Spyder",
            "nybilspris": "940000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR011",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera",
            "nybilspris": "1025000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR012",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4",
            "nybilspris": "1100000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR013",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 Cabriolet",
            "nybilspris": "1235000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR014",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S",
            "nybilspris": "1225000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR015",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S Cabriolet",
            "nybilspris": "1355000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR016",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera Cabriolet",
            "nybilspris": "1160000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR017",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S",
            "nybilspris": "1155000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR018",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S Cabriolet",
            "nybilspris": "1285000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR019",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne",
            "nybilspris": "760000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR020",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Coupé",
            "nybilspris": "830000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR022",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR019",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid, miljöbil",
            "nybilspris": "934000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR021",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR020",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid Coupé, miljöbil",
            "nybilspris": "979000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR023",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S",
            "nybilspris": "944000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR024",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S Coupé",
            "nybilspris": "995000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR025",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo",
            "nybilspris": "1414000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR026",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo Coupé",
            "nybilspris": "1464000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR028",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR025",
            "marke": "Porsche",
            "modell": "Cayenne Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1725000",
            "bransletyp": "Laddhybrid",
            "justering": "76700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR027",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR026",
            "marke": "Porsche",
            "modell": "Cayenne Turbo S E-Hybrid Coupé, miljöbil",
            "nybilspris": "1765000",
            "bransletyp": "Laddhybrid",
            "justering": "62200"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR029",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan",
            "nybilspris": "600000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR030",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan GTS",
            "nybilspris": "800000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR031",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan S",
            "nybilspris": "660000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR032",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan Turbo",
            "nybilspris": "910000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR033",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4",
            "nybilspris": "894000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR034",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4 10 Year Edition",
            "nybilspris": "1055000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR038",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR033",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid, miljöbil",
            "nybilspris": "1076000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR035",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR033",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid 10 Year Edition, miljöbil",
            "nybilspris": "1225000",
            "bransletyp": "Laddhybrid",
            "justering": "241800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR037",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR039",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1106000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR036",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR039",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid Sport Turismo 10 Year Edition, miljöbil",
            "nybilspris": "1255000",
            "bransletyp": "Laddhybrid",
            "justering": "241800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR041",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S",
            "nybilspris": "1172000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR039",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4 Sport Turismo",
            "nybilspris": "924000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR040",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4 Sport Turismo 10 Year Edition",
            "nybilspris": "1085000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR042",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S Sport Turismo",
            "nybilspris": "1222000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR043",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera GTS",
            "nybilspris": "1392000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR044",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera GTS Sport Turismo",
            "nybilspris": "1422000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR045",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo",
            "nybilspris": "1592000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR047",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR045",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1893000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR046",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR048",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1923000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR048",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo Sport Turismo",
            "nybilspris": "1622000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR050",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR031",
            "marke": "Porsche",
            "modell": "Taycan 4S, miljöbil",
            "nybilspris": "1170000",
            "bransletyp": "El",
            "justering": "98900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR051",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR033",
            "marke": "Porsche",
            "modell": "Taycan Turbo, miljöbil",
            "nybilspris": "1700000",
            "bransletyp": "El",
            "justering": "151100"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20PR049",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20PR041",
            "marke": "Porsche",
            "modell": "Taycan  Turbo S, miljöbil",
            "nybilspris": "2080000",
            "bransletyp": "El",
            "justering": "281900"
        }
    ]
}