export const seatyears = {
    "resultCount": 104,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "18SE001",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 1.4 TSI 150 Style",
            "nybilspris": "271900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE002",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 1.4 TSI 150 Style Advanced",
            "nybilspris": "284900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE003",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 150 4Drive Style Advanced",
            "nybilspris": "316900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE004",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 150 DSG6 Style Advanced",
            "nybilspris": "330400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE005",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 150 Ecomotive Style Advanced",
            "nybilspris": "310400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE006",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 184 DSG7 4Drive Style Advanced",
            "nybilspris": "333400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE055",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 184 DSG7 4Drive Swedish Edition",
            "nybilspris": "368300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE007",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 184 Style Advanced",
            "nybilspris": "317900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE061",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE011",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "181900",
            "bransletyp": "Gas",
            "justering": "12000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE062",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE011",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "169900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE008",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 FR",
            "nybilspris": "178900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE009",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Style",
            "nybilspris": "172900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE010",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Xcellence",
            "nybilspris": "178900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE011",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 95 Style",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE012",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.5 TSI 150 FR",
            "nybilspris": "189900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE063",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 115 Style",
            "nybilspris": "240900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE064",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 95 Style",
            "nybilspris": "190900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE013",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.0 TSI 115 Style",
            "nybilspris": "166900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE014",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.4 TSI 150 4Drive Style",
            "nybilspris": "240900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE015",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.4 TSI 150 ACT 4Drive DSG6 Style",
            "nybilspris": "256900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE016",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.4 TSI 150 ACT 4Drive Xcellence",
            "nybilspris": "265900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE017",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.4 TSI 150 ACT Style",
            "nybilspris": "231900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE018",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.4 TSI 150 ACT Xcellence",
            "nybilspris": "256900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE019",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.4 TSI 150 FR",
            "nybilspris": "256900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE065",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO 4Drive DSG7 FR",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE066",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO 4Drive DSG7 Xcellence",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE067",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO FR",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE068",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO Xcellence",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE069",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.6 TDI 115 Style",
            "nybilspris": "268600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE020",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 150 4Drive Xcellence",
            "nybilspris": "291900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE070",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 150 FR",
            "nybilspris": "297900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE021",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 190 4Drive DSG7 FR",
            "nybilspris": "322900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE022",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 190 4Drive DSG7 Xcellence",
            "nybilspris": "322900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE023",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TSI 190 4Drive DSG7 FR",
            "nybilspris": "296900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE024",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 MPI 75 hk",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE071",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 MPI 80 Style",
            "nybilspris": "134900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE025",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE029",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "149900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE056",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE029",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 95 FR, miljöbil",
            "nybilspris": "166900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE026",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 DSG7 Style",
            "nybilspris": "159600",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE072",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 FR",
            "nybilspris": "160900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE027",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 Xcellence",
            "nybilspris": "158900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE028",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 FR",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE029",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 hk",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE030",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 Xcellence",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE031",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.5 TSI 150 FR",
            "nybilspris": "182100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE073",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 Style",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE032",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI Ecomotive 115 DSG7 Style",
            "nybilspris": "193900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE033",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.2 TSI 110 Style",
            "nybilspris": "171900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE034",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.4 ACT 150 FR",
            "nybilspris": "207900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE057",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.4 ACT 150 FR Edition",
            "nybilspris": "212400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE035",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.4 ACT 150 Xcellence",
            "nybilspris": "207900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE036",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE033",
            "marke": "Seat",
            "modell": "Leon 1.4 TGI 110 Style, miljöbil",
            "nybilspris": "180900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE037",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.4 TSI 125 FR",
            "nybilspris": "195900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE058",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.4 TSI 125 FR Edition",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE075",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE073",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "224900",
            "bransletyp": "Gas",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE074",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE073",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "207200",
            "bransletyp": "Gas",
            "justering": "17300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE076",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE073",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "189900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE077",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR",
            "nybilspris": "217900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE078",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE079",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR",
            "nybilspris": "228900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE080",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "217900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE081",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.6 TDI 115 Style",
            "nybilspris": "197900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE082",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR",
            "nybilspris": "248900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE083",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR Edition",
            "nybilspris": "235900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE038",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 Xcellence",
            "nybilspris": "225900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE084",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 184 DSG7 FR",
            "nybilspris": "276900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE085",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 184 DSG7 FR Edition",
            "nybilspris": "263900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE086",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 190 DSG7 FR",
            "nybilspris": "265900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE087",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 190 DSG7 FR Edition",
            "nybilspris": "252900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE088",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 290 DSG7 Cupra",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE039",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 300 Cupra",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE040",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 310 Cupra R",
            "nybilspris": "399900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE089",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI 115 Style",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE041",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI Ecomotive 115 DSG7 Style",
            "nybilspris": "201900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE042",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.2 TSI 110 Style",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE043",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.4 ACT 150 FR",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE059",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.4 ACT 150 FR Edition",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE044",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.4 ACT 150 Xcellence",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE045",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE033",
            "marke": "Seat",
            "modell": "Leon ST 1.4 TGI 110 Style, miljöbil",
            "nybilspris": "188900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE046",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.4 TSI 125 FR",
            "nybilspris": "203900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE060",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.4 TSI 125 FR Edition",
            "nybilspris": "203900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE047",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.4 TSI 125 X-Perience",
            "nybilspris": "216400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE091",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE042",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "232900",
            "bransletyp": "Gas",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE090",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE042",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "226400",
            "bransletyp": "Gas",
            "justering": "28500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE092",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE042",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "197900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE093",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR",
            "nybilspris": "225900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE094",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE095",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR",
            "nybilspris": "236900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE096",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "225900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE097",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 4Drive X-Perience",
            "nybilspris": "239900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE048",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 Style",
            "nybilspris": "203900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE098",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 4Drive DSG7 FR",
            "nybilspris": "276900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE099",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 4Drive DSG7 FR Edition",
            "nybilspris": "265900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE049",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 4Drive DSG7 Xcellence",
            "nybilspris": "255900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE050",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 4Drive X-Perience",
            "nybilspris": "246900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE100",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR",
            "nybilspris": "256900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE101",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR Edition",
            "nybilspris": "245900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE051",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 Xcellence",
            "nybilspris": "233900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE102",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 4Drive X-Perience",
            "nybilspris": "279900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE103",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 FR",
            "nybilspris": "273900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE104",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 FR Edition",
            "nybilspris": "262900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE052",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 300 4Drive DSG6 Cupra",
            "nybilspris": "329900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE053",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 300 Cupra",
            "nybilspris": "307900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "18SE054",
            "filskapaddatum": "2018-11-16 00:00",
            "tillverkningsar": "2018",
            "kodforjamforbarmodell": "18SE024",
            "marke": "Seat",
            "modell": "Mii 1.0 MPI 68 EcoFuel Chic, miljöbil",
            "nybilspris": "152900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 1.4 TSI 150 Style",
            "nybilspris": "291900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 150 4Drive Xcellence",
            "nybilspris": "342900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 177 DSG7 4Drive Xcellence",
            "nybilspris": "370900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 177 DSG7 4Drive Xcellence Swedish Edition",
            "nybilspris": "379900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE010",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "184900",
            "bransletyp": "Gas",
            "justering": "12000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE010",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "169900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 FR",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Style",
            "nybilspris": "172900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Xcellence",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 95 Style",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.5 TSI 150 FR",
            "nybilspris": "195900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 95 Style",
            "nybilspris": "212900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 95 Xcellence",
            "nybilspris": "201900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.0 TSI 115 Style",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO 4Drive DSG7 FR",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 4Drive Style",
            "nybilspris": "262900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 4Drive Xcellence",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 Style",
            "nybilspris": "253900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO FR",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO Xcellence",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.6 TDI 115 Style",
            "nybilspris": "247900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 150 FR",
            "nybilspris": "297900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 190 4Drive DSG7 FR",
            "nybilspris": "337900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TSI 190 4Drive DSG7 FR",
            "nybilspris": "309900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Cupra Ateca 2.0 TSI 300 4Drive DSG7 Cupra",
            "nybilspris": "409900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 MPI 80 Style",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE032",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "189900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE033",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "178900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 FR",
            "nybilspris": "165900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 Style DSG",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 Xcellence",
            "nybilspris": "165900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 FR",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 Style",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 Xcellence",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 Ecomotive 115 DSG7 Style",
            "nybilspris": "196900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 FR",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 FR Edition",
            "nybilspris": "205900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 Style",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE036",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "224900",
            "bransletyp": "Gas",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE036",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "237900",
            "bransletyp": "Gas",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE036",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "189900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR",
            "nybilspris": "217900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 Style",
            "nybilspris": "188900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR",
            "nybilspris": "228900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR DSG",
            "nybilspris": "250900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.6 TDI 115 Style",
            "nybilspris": "197900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR",
            "nybilspris": "248900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR Edition",
            "nybilspris": "235900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 184 DSG7 FR",
            "nybilspris": "276900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 184 DSG7 FR Edition",
            "nybilspris": "263900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 290 DSG7 Cupra",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI BZ 190 DSG7 FR",
            "nybilspris": "265900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI BZ 190 DSG7 FR Edition",
            "nybilspris": "252900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 Ecomotive 115 DSG7 Style",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI 115 Style",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE053",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "232900",
            "bransletyp": "Gas",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE053",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "251900",
            "bransletyp": "Gas",
            "justering": "28500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE053",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "217900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR",
            "nybilspris": "225900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI Evo 130 Style",
            "nybilspris": "196900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR",
            "nybilspris": "236900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "225900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 4Drive X-Perience",
            "nybilspris": "239900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 4Drive X-Perience Swedish Edition",
            "nybilspris": "229900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 Style",
            "nybilspris": "205900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 DSG7 4Drive FR",
            "nybilspris": "276900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 DSG7 4Drive FR Edition",
            "nybilspris": "265900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR",
            "nybilspris": "256900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR Edition",
            "nybilspris": "245900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 4Drive X-Perience",
            "nybilspris": "279900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 4Drive X-Perience Swedish Edition",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 300 4Drive DSG7 Cupra",
            "nybilspris": "337900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI BZ 190 DSG7 FR",
            "nybilspris": "273900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI BZ 190 DSG7 FR Edition",
            "nybilspris": "262900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 1.5 TSI 150 Style",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 150 DSG7 4Drive Style",
            "nybilspris": "324900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 150 Style",
            "nybilspris": "284900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 190 DSG7 4Drive Xcellence",
            "nybilspris": "364900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 190 DSG7 4Drive Xcellence Business Edition",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TSI 190 DSG7 4Drive Xcellence",
            "nybilspris": "349900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE001",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 177 DSG7 4Drive Swedish Edition",
            "nybilspris": "429900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE002",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE007",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "205900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE003",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE007",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "195900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE004",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 FR",
            "nybilspris": "198900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE005",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Style DSG",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE006",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Xcellence DSG",
            "nybilspris": "208900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE007",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 95 Style",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE008",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 95 Style",
            "nybilspris": "222900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE009",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.0 TSI 115 Style",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE010",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 Style",
            "nybilspris": "267900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE011",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO FR",
            "nybilspris": "284900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE012",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.6 TDI 115 Style",
            "nybilspris": "264900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE013",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 150 FR",
            "nybilspris": "314900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE014",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 190 4Drive DSG7 FR",
            "nybilspris": "354900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE015",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TSI 190 4Drive DSG7 FR",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE016",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Cupra Ateca 2.0 TSI 300 4Drive DSG7 Cupra",
            "nybilspris": "409900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE017",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 MPI 80 Style",
            "nybilspris": "147900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE018",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE017",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "192900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE019",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE017",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "181900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE020",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 DSG7 Style",
            "nybilspris": "173900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE021",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 FR",
            "nybilspris": "173900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE022",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 FR",
            "nybilspris": "195900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE023",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 FR Edition",
            "nybilspris": "205900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE024",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 Style",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE026",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE024",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "225900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE025",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE024",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "237900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE027",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE024",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 Style miljöbil",
            "nybilspris": "209900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE028",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE029",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE030",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 Style",
            "nybilspris": "188900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE031",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR DSG",
            "nybilspris": "230900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE032",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR Edition DSG",
            "nybilspris": "240900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE033",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.6 TDI 115 Style",
            "nybilspris": "205900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE034",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR",
            "nybilspris": "238900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE035",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR Edition",
            "nybilspris": "263900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE036",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 290 DSG7 Cupra",
            "nybilspris": "328900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE037",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI 115 FR",
            "nybilspris": "203900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE038",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI 115 FR Edition",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE039",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI 115 Style",
            "nybilspris": "187900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE041",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE039",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "233900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE040",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE039",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "251900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE042",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE039",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "226000",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE043",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR",
            "nybilspris": "212900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE044",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE045",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 Style",
            "nybilspris": "196900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE046",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE047",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "236900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE048",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 Style",
            "nybilspris": "224900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE049",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR",
            "nybilspris": "246900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE050",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR Edition",
            "nybilspris": "258900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE051",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 300 4Drive DSG7 Cupra",
            "nybilspris": "347900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE052",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "20SE052",
            "marke": "Seat",
            "modell": "Mii electric Plus 86hk, miljöbil",
            "nybilspris": "264900",
            "bransletyp": "El",
            "justering": "-133900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE053",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 1.5 TSI 150 Style",
            "nybilspris": "285900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE054",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 150 DSG7 4Drive Style",
            "nybilspris": "350900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE055",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 150 Style",
            "nybilspris": "310900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE056",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 190 DSG7 4Drive Xcellence",
            "nybilspris": "384900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE057",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 190 DSG7 4Drive Xcellence Business Edition",
            "nybilspris": "354700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "20SE058",
            "filskapaddatum": "2019-12-16 00:00",
            "tillverkningsar": "2020",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TSI 190 DSG7 4Drive Xcellence",
            "nybilspris": "364900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}
