export const volvo = {
  next:
    "https://skatteverket.entryscape.net/rowstore/dataset/fad86bf9-67e3-4d68-829c-7b9a23bc5e42/json?_offset=100&_limit=100&fordonstyp=Personbil&tillverkningsar=2018&marke=Volvo",
  resultCount: 573,
  offset: 0,
  limit: 100,
  results: [
    {
      fordonstyp: "Personbil",
      kod: "18VO001",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Cross Country D3 Classic Plus",
      nybilspris: "299800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO002",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Cross Country D3 Classic Pro",
      nybilspris: "309700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO003",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Cross Country D4 AWD Classic Plus",
      nybilspris: "332700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO004",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Cross Country D4 AWD Classic Pro",
      nybilspris: "342600",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO005",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Cross Country D4 Classic Plus",
      nybilspris: "317800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO006",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Cross Country D4 Classic Pro",
      nybilspris: "327700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO007",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D3 Classic Momentum",
      nybilspris: "289900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO008",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D3 Classic R-Design",
      nybilspris: "305800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO009",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D3 Classic Summum",
      nybilspris: "299800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO010",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D3 e Classic Momentum",
      nybilspris: "299800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO011",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D3 e Classic Summum",
      nybilspris: "309700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO012",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 AWD Classic Momentum",
      nybilspris: "322800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO013",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 AWD Classic R-Design",
      nybilspris: "338700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO014",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 AWD Classic Summum",
      nybilspris: "332700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO015",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 Classic Momentum",
      nybilspris: "307900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO016",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 Classic R-Design",
      nybilspris: "323800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO017",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 Classic Summum",
      nybilspris: "317800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO018",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 e Classic Momentum",
      nybilspris: "317800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO019",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 D4 e Classic Summum",
      nybilspris: "327700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO020",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 Polestar AWD",
      nybilspris: "640000",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO021",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S60 T3 Classic Edition",
      nybilspris: "229900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO022",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 e Business Advanced",
      nybilspris: "348900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO023",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 e Business Advanced Plus",
      nybilspris: "375700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO024",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 e Momentum",
      nybilspris: "344000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO337",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 Inscription",
      nybilspris: "397000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO338",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 Momentum",
      nybilspris: "333000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO339",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 Momentum Advanced Edition",
      nybilspris: "350900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO340",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 Momentum Edition",
      nybilspris: "329900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO341",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 Momentum Pro Edition",
      nybilspris: "361900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO342",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D3 R-Design",
      nybilspris: "402000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO025",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 AWD Business Advanced",
      nybilspris: "402800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO026",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 AWD Business Advanced Plus",
      nybilspris: "429600",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO027",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 AWD Edition",
      nybilspris: "413900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO028",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 AWD Inscription",
      nybilspris: "481500",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO029",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 AWD Momentum",
      nybilspris: "397900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO030",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 AWD R-Design",
      nybilspris: "486500",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO031",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Business Advanced",
      nybilspris: "388800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO032",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Business Advanced Plus",
      nybilspris: "415600",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO033",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Edition",
      nybilspris: "399900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO034",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Inscription",
      nybilspris: "436900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO035",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Momentum",
      nybilspris: "372900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO343",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Momentum Advanced Edition",
      nybilspris: "390800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO344",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Momentum Edition",
      nybilspris: "369800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO345",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 Momentum Pro Edition",
      nybilspris: "401800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO036",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D4 R-Design",
      nybilspris: "441900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO037",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Inscription",
      nybilspris: "476900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO038",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Inscription Pro",
      nybilspris: "615100",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO346",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Momentum",
      nybilspris: "412900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO347",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Momentum Advanced Edition",
      nybilspris: "430800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO348",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Momentum Edition",
      nybilspris: "409800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO039",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Momentum Plus",
      nybilspris: "462600",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO349",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD Momentum Pro Edition",
      nybilspris: "441800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO040",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD R-Design",
      nybilspris: "481900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO041",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 D5 AWD R-Design Pro",
      nybilspris: "582400",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO350",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T4 Inscription",
      nybilspris: "396900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO351",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T4 Momentum",
      nybilspris: "332900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO352",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T4 Momentum Advanced Edition",
      nybilspris: "350800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO353",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T4 Momentum Edition",
      nybilspris: "329800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO354",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T4 Momentum Pro Edition",
      nybilspris: "361800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO355",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T4 R-Design",
      nybilspris: "401900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO042",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Business Advanced",
      nybilspris: "379800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO043",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Business Advanced Plus",
      nybilspris: "406600",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO044",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Inscription",
      nybilspris: "428900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO045",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Momentum",
      nybilspris: "364900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO356",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Momentum Advanced Edition",
      nybilspris: "382800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO357",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Momentum Edition",
      nybilspris: "361800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO358",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 Momentum Pro Edition",
      nybilspris: "393800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO046",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T5 R-Design",
      nybilspris: "433900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO047",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD Inscription",
      nybilspris: "488900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO048",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD Inscription Pro",
      nybilspris: "647100",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO359",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD Momentum",
      nybilspris: "424900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO360",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD Momentum Advanced Edition",
      nybilspris: "442800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO361",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD Momentum Edition",
      nybilspris: "421800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO362",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD Momentum Pro Edition",
      nybilspris: "453800",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO049",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD R-Design",
      nybilspris: "493900",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO050",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "S90 T6 AWD R-Design Pro",
      nybilspris: "614400",
      bransletyp: "Bensin",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO052",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO044",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine Inscription, miljöbil",
      nybilspris: "608900",
      bransletyp: "Laddhybrid",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO051",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO044",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine Inscription Pro, miljöbil",
      nybilspris: "797100",
      bransletyp: "Laddhybrid",
      justering: "108600"
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO366",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO045",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine Momentum, miljöbil",
      nybilspris: "544900",
      bransletyp: "Laddhybrid",
      justering: "26000"
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO363",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO356",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine Momentum Advanced Edition, miljöbil",
      nybilspris: "563800",
      bransletyp: "Laddhybrid",
      justering: "26000"
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO364",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO357",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine Momentum Edition, miljöbil",
      nybilspris: "546800",
      bransletyp: "Laddhybrid",
      justering: "26000"
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO365",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO358",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine Momentum Pro Edition, miljöbil",
      nybilspris: "575800",
      bransletyp: "Laddhybrid",
      justering: "26000"
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO054",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO046",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine R-Design, miljöbil",
      nybilspris: "613900",
      bransletyp: "Laddhybrid",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO053",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "18VO046",
      marke: "Volvo",
      modell: "S90 T8 Twin Engine R-Design Pro, miljöbil",
      nybilspris: "778400",
      bransletyp: "Laddhybrid",
      justering: "84900"
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO055",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2",
      nybilspris: "257000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO056",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2 Active",
      nybilspris: "270700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO057",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2 Business",
      nybilspris: "233800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO058",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2 Business Advanced",
      nybilspris: "255800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO059",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2 Business Advanced Pro",
      nybilspris: "280800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO060",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2 Plus",
      nybilspris: "275000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO061",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D2 Pro",
      nybilspris: "300000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO062",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3",
      nybilspris: "259000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO063",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Active",
      nybilspris: "286700",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO367",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Advanced Edition",
      nybilspris: "259900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO064",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Business",
      nybilspris: "249800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO065",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Business Advanced",
      nybilspris: "271800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO066",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Business Advanced Pro",
      nybilspris: "296800",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO368",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Edition",
      nybilspris: "239900",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO067",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Plus",
      nybilspris: "291000",
      bransletyp: "Diesel",
      justering: ""
    },
    {
      fordonstyp: "Personbil",
      kod: "18VO068",
      filskapaddatum: "2018-11-16 00:00",
      tillverkningsar: "2018",
      kodforjamforbarmodell: "",
      marke: "Volvo",
      modell: "V40 Cross Country D3 Pro",
      nybilspris: "316000",
      bransletyp: "Diesel",
      justering: ""
    }
  ]
};

export const averagePrice = () => {
  const prices = volvo.results.map(car => car.nybilspris);
  const model = volvo.results.map(car => car.marke);

  let average =
    prices.reduce(function(model, nybilspris) {
      return model + nybilspris;
    }, 0) / model.length;
  console.log(average);
};
