export const fiat = {
    "resultCount": 41,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19FI018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "124 Spider LOUNGE 1.4 140hk MT",
            "nybilspris": "284900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "124 Spider POP 1.4 140hk MT",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 0.9 85hk Lounge",
            "nybilspris": "157900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 0.9 85hk Rockstar",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 0.9 85hk Sport",
            "nybilspris": "157900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 1.2 69hk 120th Collezione",
            "nybilspris": "157900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 1.2 69hk Dolcevita",
            "nybilspris": "189900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 1.2 69hk Lounge",
            "nybilspris": "144900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 1.2 69hk Pop",
            "nybilspris": "134900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500 1.2 69hk Star",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 0.9 85hk Lounge",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 0.9 85hk Rockstar",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 0.9 85hk Sport",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 1.2 69hk 120th Collezione",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 1.2 69hk Dolcevita",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 1.2 69hk Lounge",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 1.2 69hk Pop",
            "nybilspris": "154900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500C 1.2 69hk Star",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500L CROSS 1.4 120hk MT",
            "nybilspris": "183900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500L POP STAR 1.4 120hk MT",
            "nybilspris": "173900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500L POP STAR 1.4 95hk MT",
            "nybilspris": "158900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,0 GSE T3 120HK MT FWD",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,0 GSE T3 120HK MT FWD",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,0 GSE T3 120HK MT FWD",
            "nybilspris": "209900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,3 GSE T4 150HK DDCT FWD",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,6 E-Torq 110HK MT FWD",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,6 E-Torq 110HK MT FWD",
            "nybilspris": "209900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "500X 1,6 E-Torq 110HK MT FWD",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "NYA DOBLÓ EASY 1.6 MJT 120HK",
            "nybilspris": "191900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FI036",
            "marke": "Fiat",
            "modell": "NYA DOBLÒ LOUNGE 1.4 CNG 120HK, miljöbil",
            "nybilspris": "219900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "Panda 4x4 0.9 SGE TC 85hk E6D",
            "nybilspris": "154900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "Panda Cross 4x4 0.9 SGE TC 90hk E6D",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "Panda Easy 1.2 EVO2 69hk E6D",
            "nybilspris": "116900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO HB Lounge 1,4 120hk",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO HB Lounge 1,6 120hk DDCT",
            "nybilspris": "220900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO HB Pop 1,4 95hk",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO HB Street 1,4 95HK",
            "nybilspris": "171900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO SW Lounge 1,4 120hk",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO SW Lounge 1,6 120hk DDCT",
            "nybilspris": "230900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO SW Pop 1,4 95hk",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FI041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Fiat",
            "modell": "TIPO SW Street 1,4 95HK",
            "nybilspris": "181900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}