export const ford = {
    "resultCount": 147,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19FO001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport ST-Line 1.0T 125hk",
            "nybilspris": "189900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport ST-Line 1.0T 140hk",
            "nybilspris": "222000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport ST-Line 1.5 EcoBlue 125hk AWD",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Titanium 1.0T 125hk",
            "nybilspris": "203300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Titanium 1.0T 140hk",
            "nybilspris": "211300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Titanium 1.5 EcoBlue 125hk AWD",
            "nybilspris": "243300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Trend 1.0T 100hk",
            "nybilspris": "171800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Trend 1.0T 125hk",
            "nybilspris": "178800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Trend Plus 1.0T 100hk",
            "nybilspris": "184500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Trend Plus 1.0T 125hk",
            "nybilspris": "191500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "EcoSport Trend Plus 1.5 EcoBlue 125hk AWD",
            "nybilspris": "231500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Active 1,0T 100hk",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Active 1,0T 140hk",
            "nybilspris": "199300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Active 1,5 TDCi 120hk",
            "nybilspris": "224800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Active 1,5 TDCi 85hk",
            "nybilspris": "206800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta ST 200hk",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta ST-Line 1,0T 100hk",
            "nybilspris": "183300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta ST-Line 1,0T 140hk",
            "nybilspris": "198300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta ST-Line 1,5TDCi 120hk",
            "nybilspris": "223800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Titanium 1,0T 100hk",
            "nybilspris": "177300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Titanium 1,1 85hk",
            "nybilspris": "165800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Titanium 1,5 TDCi 120hk",
            "nybilspris": "213800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Titanium 1,5 TDCi 85hk",
            "nybilspris": "195800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Trend 1,1 85hk",
            "nybilspris": "155800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Trend 1,5 TDCi 85hk",
            "nybilspris": "185800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Trend Plus 1,0T 100hk",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Vignale 1,0T 100hk",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Fiesta Vignale 1,0T 140hk",
            "nybilspris": "213800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Galaxy Titanium 2.0 EcoBlue 150hk",
            "nybilspris": "325100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Galaxy Titanium 2.0 EcoBlue 190hk",
            "nybilspris": "372400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Galaxy Trend 2.0 EcoBlue 120hk",
            "nybilspris": "319200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Galaxy Trend 2.0 EcoBlue 150hk",
            "nybilspris": "333200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line 1.5T 150hk",
            "nybilspris": "269000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line 1.5T 176hk AUT AWD",
            "nybilspris": "310500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line 1.5 TDCi 120hk",
            "nybilspris": "282500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line 2.0T 230hk AUT AWD",
            "nybilspris": "342500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line 2.0TDCi 150hk AWD",
            "nybilspris": "309500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line 2.0TDCi 180hk AWD",
            "nybilspris": "322500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO119",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO034",
            "marke": "Ford",
            "modell": "Kuga ST-Line Edition 1.5T 150hk E85,miljöbil",
            "nybilspris": "274900",
            "bransletyp": "Alkohol",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line Edition 2.0T 230hk AUT AWD",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line Edition 2.0TDCi 180hk AWD",
            "nybilspris": "319900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga ST-Line Limited 1.5T 150hk",
            "nybilspris": "259900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Titanium 1.5T 150hk",
            "nybilspris": "251000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Titanium 1.5T 176hk AUT AWD",
            "nybilspris": "292500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Titanium 1.5 TDCi 120hk",
            "nybilspris": "264500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Titanium 2.0 TDCi 150hk AWD",
            "nybilspris": "291500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Titanium 2.0 TDCi 180hk AWD",
            "nybilspris": "304500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO120",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO043",
            "marke": "Ford",
            "modell": "Kuga Titanium Edition 1.5T 150hk E85, miljöbil",
            "nybilspris": "259900",
            "bransletyp": "Alkohol",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Trend 1.5T 150hk",
            "nybilspris": "222500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Trend 1.5 TDCi 120hk",
            "nybilspris": "236000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Trend 2.0 TDCi 150hk AWD",
            "nybilspris": "263000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO121",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO034",
            "marke": "Ford",
            "modell": "Kuga Vignale 1.5T 150hk AUT E85,miljöbil",
            "nybilspris": "304900",
            "bransletyp": "Alkohol",
            "justering": "30000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Vignale 2.0TDCi 150hk MPS AWD",
            "nybilspris": "355000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Kuga Vignale 2.0TDCi 180hk MPS AWD",
            "nybilspris": "333900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo ST-Line 2.0 TDCi 180hk MPS AWD",
            "nybilspris": "333700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo ST-Line Kombi 2.0 TDCi 180hk MPS AWD",
            "nybilspris": "341200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Titanium 1.5T 165 hk",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Titanium 2.0 TDCi 150hk",
            "nybilspris": "278900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Titanium 2.0 TDCi 180hk",
            "nybilspris": "296400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO056",
            "marke": "Ford",
            "modell": "Mondeo Titanium Hybrid 4D 2.0 HEV 187hk, miljöbil",
            "nybilspris": "299900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Titanium Kombi 1.5T 165hk",
            "nybilspris": "272400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Titanium Kombi 2.0 TDCi 150hk",
            "nybilspris": "286400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Titanium Kombi 2.0 TDCi 180hk",
            "nybilspris": "303900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Vignale 5d 2.0 TDCi 180hk MPS",
            "nybilspris": "371000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO061",
            "marke": "Ford",
            "modell": "Mondeo Vignale Hybrid 4D 2.0 HEV 187hk, miljöbil",
            "nybilspris": "372900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mondeo Vignale Kombi 2.0TDCi 180hk MPS",
            "nybilspris": "378500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO127",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mustang BULLITT Fastback 5.0 V8 450hk",
            "nybilspris": "538500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mustang Convertible 2.3T 290hk",
            "nybilspris": "438500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mustang Convertible 5.0 V8 450hk",
            "nybilspris": "506500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mustang Fastback 2.3T 290hk",
            "nybilspris": "394500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Mustang Fastback 5.0 V8 450hk",
            "nybilspris": "462500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Edge ST-Line 2,0 EcoBlue 240hk AUT AWD",
            "nybilspris": "454900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Edge Titanium 2,0 EcoBlue 240hk AUT AWD",
            "nybilspris": "462900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Edge Vignale 2,0 EcoBlue 240hk AUT AWD",
            "nybilspris": "507900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO128",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO142",
            "marke": "Ford",
            "modell": "Nya Explorer ST-Line Plug-In Hybrid, miljöbil",
            "nybilspris": "799000",
            "bransletyp": "Laddhybrid",
            "justering": "196800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active 1.0T 125hk",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active 1.5 EcoBlue 120hk",
            "nybilspris": "247400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active 1.5T 150hk",
            "nybilspris": "239400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active 1.5T 182hk AUT",
            "nybilspris": "272400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active 2.0 EcoBlue 150hk",
            "nybilspris": "267400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO129",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active Launch Edition 1.0T 125hk",
            "nybilspris": "222900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO130",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Active Launch Edition 1.5T 150hk",
            "nybilspris": "234900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active 1.0T 125hk",
            "nybilspris": "205900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active 1.5 EcoBlue 120hk",
            "nybilspris": "253400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active 1.5T 150hk",
            "nybilspris": "245400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active 1.5T 182hk AUT",
            "nybilspris": "278400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active 2.0 EcoBlue 150hk",
            "nybilspris": "273400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO122",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active Business Edition 1.5T 182hk AUT",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO123",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active Business Edition 2.0 EcoBlue 150hk AUT",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO131",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active Launch Edition 1.0T 125hk",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO132",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Active Launch Edition 1.5T 150hk",
            "nybilspris": "241900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST-Line 1.0T 125hk",
            "nybilspris": "233400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST-Line 1.5 EcoBlue 120hk",
            "nybilspris": "253400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST-Line 1.5T 150hk",
            "nybilspris": "245400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO084",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST-Line 2.0 EcoBlue 150hk",
            "nybilspris": "273400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO085",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST-Line Limited 1.0T 125hk",
            "nybilspris": "213900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO135",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST-Line Limited 1.5T 150hk",
            "nybilspris": "241900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO133",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST PLUS 2.0T EcoBlue 190hk",
            "nybilspris": "339900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO134",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi ST PLUS 2.3T EcoBoost 280hk",
            "nybilspris": "339900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO086",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Titanium 1.0T 125hk",
            "nybilspris": "226900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO087",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Titanium 1.5 EcoBlue 120hk",
            "nybilspris": "246900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO088",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Titanium 1.5T 150hk",
            "nybilspris": "238900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO089",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Titanium Limited 1.0T 125hk",
            "nybilspris": "212900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO136",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Titanium Limited 1.5T 150hk",
            "nybilspris": "234900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO090",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Trend Edition 1.0T 100hk",
            "nybilspris": "185900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO091",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Trend Edition 1.5 EcoBlue 95hk",
            "nybilspris": "215900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO092",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Vignale 1.5T 150hk AUT",
            "nybilspris": "290900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO093",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Vignale 1.5T 182hk",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO094",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Kombi Vignale 2.0 EcoBlue 150hk AUT",
            "nybilspris": "318900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO095",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST-Line 1.0T 125hk",
            "nybilspris": "227400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO096",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST-Line 1.5 EcoBlue 120hk",
            "nybilspris": "247400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO097",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST-Line 1.5T 150hk",
            "nybilspris": "239400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO098",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST-Line 2.0 EcoBlue 150hk",
            "nybilspris": "267400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO099",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST-Line Limited 1.0T 125hk",
            "nybilspris": "212900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO139",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST-Line Limited 1.5T 150hk",
            "nybilspris": "234900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO137",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST PLUS 2.0T EcoBlue 190hk",
            "nybilspris": "332900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO138",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus ST PLUS 2.3T EcoBoost 280hk",
            "nybilspris": "322900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO100",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Titanium 1.0T 125hk",
            "nybilspris": "220900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO101",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Titanium 1.5 EcoBlue 120hk",
            "nybilspris": "240900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO102",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Titanium 1.5T 150hk",
            "nybilspris": "232900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO103",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Titanium Limited 1.0T 125hk",
            "nybilspris": "205900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO140",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Titanium Limited 1.5T 150hk",
            "nybilspris": "226900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO104",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Trend Edition 1.0T 100hk",
            "nybilspris": "179900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO105",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Trend Edition 1.5 EcoBlue 95hk",
            "nybilspris": "209900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO106",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Vignale 1.5T 150hk AUT",
            "nybilspris": "284900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO107",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Vignale 1.5T 182hk",
            "nybilspris": "283900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO108",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Focus Vignale 2.0 EcoBlue 150hk AUT",
            "nybilspris": "312900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO141",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO142",
            "marke": "Ford",
            "modell": "Nya Kuga ST-Line Plug-In Hybrid, miljöbil",
            "nybilspris": "419900",
            "bransletyp": "Laddhybrid",
            "justering": "13000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO142",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Kuga Titanium 1.5T 150hk",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO143",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO142",
            "marke": "Ford",
            "modell": "Nya Kuga Titanium Plug-In Hybrid,miljöbil",
            "nybilspris": "389900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO144",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi ST-Line 2.0 EcoBlue AUT AWD 190hk",
            "nybilspris": "363400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO145",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO124",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi ST-Line 2.0 HEV AUT 187hk, miljöbil",
            "nybilspris": "396600",
            "bransletyp": "Elhybrid",
            "justering": "56500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO124",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi Titanium 1.5T 165hk AUT",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO125",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi Titanium 2.0 EcoBlue AUT AWD 190hk",
            "nybilspris": "339900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO126",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO124",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi Titanium 2.0 HEV AUT 187hk, miljöbil",
            "nybilspris": "299900",
            "bransletyp": "Elhybrid",
            "justering": "33000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO146",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi Vignale 2.0 EcoBlue AUT AWD 190hk",
            "nybilspris": "389900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO147",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19FO124",
            "marke": "Ford",
            "modell": "Nya Mondeo kombi Vignale 2.0 HEV AUT 187hk, miljöbil",
            "nybilspris": "389900",
            "bransletyp": "Elhybrid",
            "justering": "84000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO109",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max ST-Line 2.0 EcoBlue 150hk AUT",
            "nybilspris": "348900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO110",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max ST-Line 2.0 EcoBlue 190hk AUT",
            "nybilspris": "361900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO111",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max ST-Line 2.0 EcoBlue 240hk AUT",
            "nybilspris": "381900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO112",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Titanium 2.0 EcoBlue 150hk",
            "nybilspris": "310900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO113",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Titanium 2.0 EcoBlue 190hk",
            "nybilspris": "323900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO114",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Titanium 2.0 EcoBlue 240hk AUT",
            "nybilspris": "362100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO115",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Trend 2.0 EcoBlue 120hk",
            "nybilspris": "304200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO116",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Trend 2.0 EcoBlue 150hk",
            "nybilspris": "318200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO117",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Vignale 2.0 EcoBlue 190hk AUT",
            "nybilspris": "366900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19FO118",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Ford",
            "modell": "S-Max Vignale 2.0 EcoBlue 240hk AUT",
            "nybilspris": "386900",
            "bransletyp": "Diesel",
            "justering": ""
        }
    ]
}