export const hyundai = {
    "resultCount": 157,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19HY044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.0 T-GDi 100hk 5D Premium",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.0 T-GDi 100hk 5D Trend",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.0 T-GDi 120hk 5D Premium",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.0 T-GDi 120hk 5D Trend",
            "nybilspris": "154900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.25 84hk 5D Life",
            "nybilspris": "119900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.25 84hk 5D Premium",
            "nybilspris": "154900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "1.25 84hk 5D Trend",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i10 1.0 Comfort",
            "nybilspris": "117900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i10 1.0 Life",
            "nybilspris": "99900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i10 1.0 Premium",
            "nybilspris": "119900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i10 1.0 Trend",
            "nybilspris": "109900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i10 1.25 Premium",
            "nybilspris": "124900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i10 1.25 Trend",
            "nybilspris": "114900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0t-100 Comfort",
            "nybilspris": "152900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0t-100 Premium",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY120",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0 T-GDi 100hk 5D Life",
            "nybilspris": "129900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY121",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0 T-GDi 100hk 5D Premium",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY122",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0 T-GDi 100hk 5D Trend",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY123",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0 T-GDi 100hk DCT 5D Life",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY124",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0 T-GDi 120hk 5D Premium",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY125",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.0 T-GDi 120hk 5D Trend",
            "nybilspris": "154900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY126",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.25 84hk 5D Life",
            "nybilspris": "119900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY128",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i201.25 84hk 5D Premium",
            "nybilspris": "154900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY127",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.25 84hk 5D Trend",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1.2 Premium",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i20 1. Comfort",
            "nybilspris": "134900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.0 T-Gdi Life",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.0 T-Gdi Premium",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.0 T-Gdi Trend",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.0 Turbo Comfort",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.0 Turbo Select",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY129",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.4 T-Gdi DCT Life",
            "nybilspris": "189900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.4 T-Gdi Premium",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.4 T-Gdi Trend",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.4 Turbo Comfort",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.4 Turbo Premium",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.6 CRDi 115hk Premium",
            "nybilspris": "219900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.6 CRDi 115hk Trend",
            "nybilspris": "204900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.6 CRDi 136hk DCT Premium",
            "nybilspris": "249900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.6 CRDi 136hk DCT Trend",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.6 CRDi 136hk Premium",
            "nybilspris": "224900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5D 1.6 CRDi 136hk Trend",
            "nybilspris": "209900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.6 Diesel AUT-D7 Comfort",
            "nybilspris": "224900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.6 Diesel ComfortEco",
            "nybilspris": "209900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 1.6 Diesel Premium",
            "nybilspris": "249900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 2.0 Turbo N (250 hk)",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 5d 2.0 Turbo N Performance (275 hk)",
            "nybilspris": "324900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY130",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Fastback 1.0 T-Gdi 120hk Premium",
            "nybilspris": "209900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY131",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Fastback 1.0 T-Gdi 120hk Trend",
            "nybilspris": "189900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY132",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Fastback 1.4 T-GDi 140hk Premium",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY133",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Fastback 1.4 T-GDi 140hk Trend",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY134",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Fastback 1.6 CRDi 136hk Premium",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY135",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Fastback 1.6 CRDi 136hk Trend",
            "nybilspris": "224900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.0 T-Gdi Life",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.0 T-Gdi Premium",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.0 T-Gdi Trend",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.0 Turbo Comfort",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.0 Turbo Select",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY136",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.4 T-GDi DCT Life",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.4 T-Gdi Premium",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.4 T-Gdi Trend",
            "nybilspris": "194900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.4 Turbo Comfort",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.4 Turbo Premium",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.6 CRDi 115hk Premium",
            "nybilspris": "229900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.6 CRDi 115hk Trend",
            "nybilspris": "214900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.6 CRDi 136hk Premium",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.6 CRDi 136hk Trend",
            "nybilspris": "219900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.6 Diesel Comfort",
            "nybilspris": "219900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 Kombi 1.6 Diesel Premium",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 N 2.0 T-GDi 250HK",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 N 2.0 T-Gdi 275HK Performance",
            "nybilspris": "329900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY137",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 N 2.0 T-GDi Fastback 250HK",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY138",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "i30 N 2.0 T-Gdi Fastback 275HK Performance",
            "nybilspris": "339900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Electric ComfortEco, miljöbil",
            "nybilspris": "376900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Electric PremiumEco, miljöbil",
            "nybilspris": "394900",
            "bransletyp": "El",
            "justering": "18000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Electric PremiumPlusEco, miljöbil",
            "nybilspris": "409900",
            "bransletyp": "El",
            "justering": "33000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY059",
            "marke": "Hyundai",
            "modell": "IONIQ EV Premium,miljöbil",
            "nybilspris": "394900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY059",
            "marke": "Hyundai",
            "modell": "IONIQ EV Premium +, miljöbil",
            "nybilspris": "414900",
            "bransletyp": "El",
            "justering": "12900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY060",
            "marke": "Hyundai",
            "modell": "IONIQ EV Trend,miljöbil",
            "nybilspris": "374900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY059",
            "marke": "Hyundai",
            "modell": "IONIQ HEV Premium,miljöbil",
            "nybilspris": "279900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY059",
            "marke": "Hyundai",
            "modell": "IONIQ HEV Premium +, miljöbil",
            "nybilspris": "299900",
            "bransletyp": "Elhybrid",
            "justering": "12900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY060",
            "marke": "Hyundai",
            "modell": "IONIQ HEV Trend,miljöbil",
            "nybilspris": "259900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Hybrid ComfortEco, miljöbil",
            "nybilspris": "254900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Hybrid PremiumEco, miljöbil",
            "nybilspris": "289900",
            "bransletyp": "Elhybrid",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Hybrid PremiumPlusEco, miljöbil",
            "nybilspris": "304900",
            "bransletyp": "Elhybrid",
            "justering": "50000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY085",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY059",
            "marke": "Hyundai",
            "modell": "IONIQ PHEV Premium, miljöbil",
            "nybilspris": "339900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY084",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY059",
            "marke": "Hyundai",
            "modell": "IONIQ PHEV Premium +,miljöbil",
            "nybilspris": "359900",
            "bransletyp": "Laddhybrid",
            "justering": "12900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY086",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY060",
            "marke": "Hyundai",
            "modell": "IONIQ PHEV Trend, miljöbil",
            "nybilspris": "319900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Plug-in ComfortEco, miljöbil",
            "nybilspris": "324900",
            "bransletyp": "Laddhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Plug-in PremiumEco, miljöbil",
            "nybilspris": "342900",
            "bransletyp": "Laddhybrid",
            "justering": "18000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY006",
            "marke": "Hyundai",
            "modell": "IONIQ Plug-in PremiumPlusEco, miljöbil",
            "nybilspris": "357900",
            "bransletyp": "Laddhybrid",
            "justering": "33000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY139",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY098",
            "marke": "Hyundai",
            "modell": "KONA 1,6 HEV Gdi DCT Life, miljöbil",
            "nybilspris": "239900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY140",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY097",
            "marke": "Hyundai",
            "modell": "KONA 1,6 HEV Gdi DCT Premium, miljöbil",
            "nybilspris": "274900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY141",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY098",
            "marke": "Hyundai",
            "modell": "KONA 1,6 HEV Gdi DCT Trend, miljöbil",
            "nybilspris": "259900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY087",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.0 T-GDi 2WD Life",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY088",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.0 T-GDi 2WD Premium",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY089",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.0 T-GDi 2WD Trend",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY090",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 115hk Life",
            "nybilspris": "184900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY091",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 115hk Premium",
            "nybilspris": "229900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY092",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 115hk Trend",
            "nybilspris": "204900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY093",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 136hk DCT 2WD Premium",
            "nybilspris": "244900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY094",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 136hk DCT 2WD Trend",
            "nybilspris": "219900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY095",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 136hk DCT 4WD Premium",
            "nybilspris": "259900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY096",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 CRDi 136hk DCT 4WD Trend",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY097",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 T-GDi DCT 2WD Premium",
            "nybilspris": "234900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY098",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 T-GDi DCT 2WD Trend",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY099",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 T-GDi DCT 4WD Premium",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY100",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "KONA 1.6 T-GDi DCT 4WD Trend",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY142",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY098",
            "marke": "Hyundai",
            "modell": "KONA EV 39,2 kWh Life, miljöbil",
            "nybilspris": "364900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY143",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY097",
            "marke": "Hyundai",
            "modell": "KONA EV 39,2 kWh Premium, miljöbil",
            "nybilspris": "399900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY101",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY089",
            "marke": "Hyundai",
            "modell": "KONA EV 39 kWh Trend, miljöbil",
            "nybilspris": "359900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY144",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY098",
            "marke": "Hyundai",
            "modell": "KONA EV 64 kWh Life, miljöbil",
            "nybilspris": "409900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY102",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY097",
            "marke": "Hyundai",
            "modell": "KONA EV 64 kWh Premium, miljöbil",
            "nybilspris": "444900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY145",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY097",
            "marke": "Hyundai",
            "modell": "KONA EV 64 kWh Premium+, miljöbil",
            "nybilspris": "459900",
            "bransletyp": "El",
            "justering": "11900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY103",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY098",
            "marke": "Hyundai",
            "modell": "KONA EV 64 kWh Trend, miljöbil",
            "nybilspris": "409900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY104",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY114",
            "marke": "Hyundai",
            "modell": "NEXO Premium, miljöbil",
            "nybilspris": "879900",
            "bransletyp": "Gas",
            "justering": "15000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY105",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY115",
            "marke": "Hyundai",
            "modell": "NEXO Trend, miljöbil",
            "nybilspris": "849900",
            "bransletyp": "Gas",
            "justering": "15000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY146",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 150hk 2WD Life",
            "nybilspris": "349900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY147",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 150hk 2WD Premium",
            "nybilspris": "414900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY148",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 150hk 2WD Trend",
            "nybilspris": "374900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY149",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 150hk 4WD Premium",
            "nybilspris": "424900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY150",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 150hk 4WD Trend",
            "nybilspris": "384900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY151",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 185hk DCT 4WD Premium",
            "nybilspris": "444900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY152",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,0 CRDi 185hk DCT 4WD Trend",
            "nybilspris": "404900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY153",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,2 CRDi 200hk 4WD Premium",
            "nybilspris": "424900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY154",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,2 CRDi 200hk 4WD Trend",
            "nybilspris": "394900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY155",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,4 GDI 188hk DCT 4WD Life",
            "nybilspris": "349900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY156",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,4 GDI 188hk DCT 4WD Premium",
            "nybilspris": "414900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY157",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Santa Fe 2,4 GDI 188hk DCT 4WD Trend",
            "nybilspris": "374900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY106",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 CRDi 115hk 2WD Life",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY107",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 CRDi 115hk 2WD Trend",
            "nybilspris": "254900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY110",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 CRDi 136hk 2WD Premium",
            "nybilspris": "299900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY111",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 CRDi 136hk 2WD Trend",
            "nybilspris": "264900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY108",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 CRDi 136hk  4WD Premium",
            "nybilspris": "319900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY109",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 CRDi 136hk  4WD Trend",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 GDI 2WD Comfort",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY112",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 GDi 2WD Life",
            "nybilspris": "209900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 GDI 2WD Select",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY113",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 GDi 2WD Trend",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-GDI 2WD Comfort",
            "nybilspris": "254900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY114",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-Gdi 2WD Premium",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY115",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-Gdi 2WD Trend",
            "nybilspris": "254900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-GDI 4WD Comfort",
            "nybilspris": "274900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-GDI 4WD ComfortPlus",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-GDi 4WD Premium",
            "nybilspris": "304900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY117",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-Gdi 4WD Trend",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY158",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-GDi DCT 2WD DCT Life",
            "nybilspris": "254900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.6 T-GDI DCT-7 4WD S",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.7 CRDi 2WD Comfort",
            "nybilspris": "254900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.7 CRDi 2WD Select",
            "nybilspris": "224900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 1.7 CRDi DCT-7 2WD ComfortPlus",
            "nybilspris": "309900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 2.0 CRDi (136) 2WD Comfort",
            "nybilspris": "274900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 2.0 CRDi (136) 4WD Comfort",
            "nybilspris": "294900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 2.0 CRDi (136) 4WD ComfortPlus",
            "nybilspris": "319900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Hyundai",
            "modell": "Tucson 2.0 CRDi (185) 4WD Premium",
            "nybilspris": "359900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY118",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY108",
            "marke": "Hyundai",
            "modell": "Tucson 2.0 CRDi 185hk 4WD 48V MHEV Premium, miljöbil",
            "nybilspris": "339900",
            "bransletyp": "Elhybrid",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19HY119",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19HY109",
            "marke": "Hyundai",
            "modell": "Tucson 2.0 CRDi 185hk 4WD 48V MHEV Trend, miljöbil",
            "nybilspris": "304900",
            "bransletyp": "Elhybrid",
            "justering": "5000"
        }
    ]
}