export const porsche = {
    "resultCount": 51,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19PR001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster",
            "nybilspris": "570000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster GTS",
            "nybilspris": "790000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster S",
            "nybilspris": "693000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Boxster T",
            "nybilspris": "660000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman",
            "nybilspris": "549000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GT4",
            "nybilspris": "965000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman GTS",
            "nybilspris": "769000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman S",
            "nybilspris": "672000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Cayman T",
            "nybilspris": "639000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "718 Spyder",
            "nybilspris": "940000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera",
            "nybilspris": "1025000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4",
            "nybilspris": "1100000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 Cabriolet",
            "nybilspris": "1235000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 GTS",
            "nybilspris": "1312000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4 GTS Cabriolet",
            "nybilspris": "1433000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S",
            "nybilspris": "1225000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera 4S Cabriolet",
            "nybilspris": "1355000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera Cabriolet",
            "nybilspris": "1160000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera GTS",
            "nybilspris": "1203000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera GTS Cabriolet",
            "nybilspris": "1324000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S",
            "nybilspris": "1155000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Carrera S Cabriolet",
            "nybilspris": "1285000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 GT3 RS",
            "nybilspris": "1950000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "911 Targa 4 GTS",
            "nybilspris": "1433000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne",
            "nybilspris": "745000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Coupé",
            "nybilspris": "830000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR011",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid, miljöbil",
            "nybilspris": "915000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR041",
            "marke": "Porsche",
            "modell": "Cayenne E-Hybrid Coupé, miljöbil",
            "nybilspris": "979000",
            "bransletyp": "Laddhybrid",
            "justering": "27500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S",
            "nybilspris": "925000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne S Coupé",
            "nybilspris": "995000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo",
            "nybilspris": "1385000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Cayenne Turbo Coupé",
            "nybilspris": "1464000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR014",
            "marke": "Porsche",
            "modell": "Cayenne Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1725000",
            "bransletyp": "Laddhybrid",
            "justering": "76700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR044",
            "marke": "Porsche",
            "modell": "Cayenne Turbo S E-Hybrid Coupé, miljöbil",
            "nybilspris": "1765000",
            "bransletyp": "Laddhybrid",
            "justering": "62200"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan",
            "nybilspris": "600000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan S",
            "nybilspris": "660000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Macan Turbo",
            "nybilspris": "910000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4",
            "nybilspris": "877000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR016",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid, miljöbil",
            "nybilspris": "1059000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR019",
            "marke": "Porsche",
            "modell": "Panamera 4 E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1089000",
            "bransletyp": "Laddhybrid",
            "justering": "41700"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S",
            "nybilspris": "1172000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4 Sport Turismo",
            "nybilspris": "907000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera 4S Sport Turismo",
            "nybilspris": "1222000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera GTS",
            "nybilspris": "1375000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera GTS Sport Turismo",
            "nybilspris": "1405000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo",
            "nybilspris": "1569000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR025",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid, miljöbil",
            "nybilspris": "1870000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR025",
            "marke": "Porsche",
            "modell": "Panamera Turbo S E-Hybrid Sport Turismo, miljöbil",
            "nybilspris": "1900000",
            "bransletyp": "Laddhybrid",
            "justering": "198300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Porsche",
            "modell": "Panamera Turbo Sport Turismo",
            "nybilspris": "1599000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR016",
            "marke": "Porsche",
            "modell": "Taycan Turbo, miljöbil",
            "nybilspris": "1700000",
            "bransletyp": "El",
            "justering": "151100"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19PR050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19PR048",
            "marke": "Porsche",
            "modell": "Taycan  Turbo S, miljöbil",
            "nybilspris": "2080000",
            "bransletyp": "El",
            "justering": "281900"
        }
    ]
}