export const renault = {
    "resultCount": 93,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19RE001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Captur Intens Energy TCe 90",
            "nybilspris": "187900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Captur Intens TCe 150 EDC GPF",
            "nybilspris": "237900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Captur Life Energy TCe 90",
            "nybilspris": "161900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Captur Outdoor Energy TCe 90",
            "nybilspris": "201900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Captur Outdoor TCe 150 EDC GPF",
            "nybilspris": "251900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Captur Zen Energy TCe 90",
            "nybilspris": "175900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Hatchback Intens Energy dCi 90",
            "nybilspris": "198900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Hatchback Intens Energy TCe 90",
            "nybilspris": "170900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Hatchback Life Energy TCe 75",
            "nybilspris": "135900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Hatchback Zen Energy dCi 90",
            "nybilspris": "184900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Hatchback Zen Energy TCe 75",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Hatchback Zen Energy TCe 90",
            "nybilspris": "156900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Sport Tourer Intens Energy dCi 90",
            "nybilspris": "205900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Sport Tourer Intens Energy TCe 90",
            "nybilspris": "177900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Sport Tourer Life Energy TCe 75",
            "nybilspris": "142900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Sport Tourer Zen Energy dCi 90",
            "nybilspris": "191900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Sport Tourer Zen Energy TCe 75",
            "nybilspris": "156900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Clio Sport Tourer Zen Energy TCe 90",
            "nybilspris": "163900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Espace Zen Blue dCi 160 EDC",
            "nybilspris": "391900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Espace Zen Blue dCi 200 EDC",
            "nybilspris": "410900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Bose Blue dCi 120 EDC",
            "nybilspris": "310900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Bose Blue dCi 150 EDC",
            "nybilspris": "329900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Bose Tce 140 GPF EDC",
            "nybilspris": "292900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Bose Tce 160 GPF EDC",
            "nybilspris": "302900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Zen Blue dCi 120 EDC",
            "nybilspris": "281900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Zen TCe 140 GPF",
            "nybilspris": "248900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Grand Scenic Zen TCe 140 GPF EDC",
            "nybilspris": "263900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Black Blue dCi 115 EDC",
            "nybilspris": "324900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Black Blue dCi 150 4WD",
            "nybilspris": "342900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Black Tce 140 GPF EDC",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Black Tce 160 GPF EDC",
            "nybilspris": "305900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Bose Blue dCi 115 EDC",
            "nybilspris": "304900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Bose Blue dCi 150 4WD",
            "nybilspris": "322900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Bose Energy TCe 140 GPF",
            "nybilspris": "254900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Bose Tce 140 GPF EDC",
            "nybilspris": "279900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Bose Tce 160 GPF EDC",
            "nybilspris": "285900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Life Blue dCi 115",
            "nybilspris": "228900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Life Energy TCe 140 GPF",
            "nybilspris": "200900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Limited Energy TCe 140 GPF",
            "nybilspris": "233900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Zen Blue dCi 115",
            "nybilspris": "260900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Zen Blue dCi 115 EDC",
            "nybilspris": "277900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Zen Energy TCe 140 GPF",
            "nybilspris": "229900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Kadjar Zen Energy TCe 140 GPF EDC",
            "nybilspris": "252900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Koleos Intens dCi 175 4WD X-tronic Business Edition",
            "nybilspris": "309900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Koleos Intens Energy dCi 175 2WD X-tronic",
            "nybilspris": "323900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Koleos Intens Energy dCi 175 4WD X-tronic",
            "nybilspris": "343900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Master kombi 145 hk",
            "nybilspris": "387800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Master kombi 165 hk",
            "nybilspris": "392800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Bose Blue dCi 115 EDC",
            "nybilspris": "261900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Bose TCe 140 GPF",
            "nybilspris": "237900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Bose TCe 140 GPF EDC",
            "nybilspris": "253900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Bose TCe 160 GPF EDC",
            "nybilspris": "259900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Life Blue dCi 115",
            "nybilspris": "196900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Life Blue dCi 95",
            "nybilspris": "189900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Life TCe 115 GPF",
            "nybilspris": "180900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback R.S. 280 TCe 280",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Trophy 300 TCe  300",
            "nybilspris": "339900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Zen Blue dCi 115",
            "nybilspris": "221900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Zen Blue dCi 115 EDC",
            "nybilspris": "236900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Zen TCe 115 GPF",
            "nybilspris": "203900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Zen TCe 140 GPF",
            "nybilspris": "212900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Hatchback Zen TCe 140 GPF EDC",
            "nybilspris": "228900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Bose Blue dCi 115 EDC",
            "nybilspris": "271900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Bose Blue dCi 150 EDC",
            "nybilspris": "292900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Bose TCe 140 GPF",
            "nybilspris": "247900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Bose TCe 140 GPF EDC",
            "nybilspris": "263900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Bose TCe 160 GPF EDC",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Life Blue dCi 115",
            "nybilspris": "206900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Life Blue dCi 95",
            "nybilspris": "199900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Life TCe 115 GPF",
            "nybilspris": "190900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Zen Blue dCi 115",
            "nybilspris": "231900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE084",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Zen Blue dCi 115 EDC",
            "nybilspris": "246900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Zen TCe 115 GPF",
            "nybilspris": "213900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Zen TCe 140 GPF",
            "nybilspris": "222900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE085",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Megane Sport Tourer Zen TCe 140 GPF EDC",
            "nybilspris": "238900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Intens Blue dCi 120",
            "nybilspris": "292900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Intens Blue dCi 150",
            "nybilspris": "312900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE086",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Intens Blue dCi 200 EDC Business Edition",
            "nybilspris": "325900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE087",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Intens TCe 225 EDC GPF Business Edition",
            "nybilspris": "302900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Intens Tce 225 GPF EDC",
            "nybilspris": "322900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Life Blue dCi 120",
            "nybilspris": "246900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Zen Blue dCi 120",
            "nybilspris": "266900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Talisman Zen Blue dCi 150",
            "nybilspris": "286900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Trafic Passenger 120 hk",
            "nybilspris": "356600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE088",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Renault",
            "modell": "Trafic Passenger 120 hk L2H1",
            "nybilspris": "362800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE006",
            "marke": "Renault",
            "modell": "Zoe Bose 41 kWh, miljöbil",
            "nybilspris": "367900",
            "bransletyp": "El",
            "justering": "20000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE090",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE006",
            "marke": "Renault",
            "modell": "Zoe Edition One 52 kWh, miljöbil",
            "nybilspris": "399900",
            "bransletyp": "El",
            "justering": "13000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE089",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE006",
            "marke": "Renault",
            "modell": "Zoe Iconic 41 kWh, miljöbil",
            "nybilspris": "356900",
            "bransletyp": "El",
            "justering": "5000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE006",
            "marke": "Renault",
            "modell": "Zoe Intens 41 kWh, miljöbil",
            "nybilspris": "348900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE091",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE006",
            "marke": "Renault",
            "modell": "Zoe Intens 52 kWh, miljöbil",
            "nybilspris": "386900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE007",
            "marke": "Renault",
            "modell": "Zoe Life 41 kWh, miljöbil",
            "nybilspris": "329900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE092",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE007",
            "marke": "Renault",
            "modell": "Zoe Life 52 kWh, miljöbil",
            "nybilspris": "352900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19RE093",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19RE009",
            "marke": "Renault",
            "modell": "Zoe Zen 52 kWh, miljöbil",
            "nybilspris": "366900",
            "bransletyp": "El",
            "justering": ""
        }
    ]
}