export const seat = {
    "resultCount": 83,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19SE001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 1.4 TSI 150 Style",
            "nybilspris": "291900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 150 4Drive Xcellence",
            "nybilspris": "342900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 177 DSG7 4Drive Xcellence",
            "nybilspris": "370900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Alhambra 2.0 TDI 177 DSG7 4Drive Xcellence Swedish Edition",
            "nybilspris": "379900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE010",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "184900",
            "bransletyp": "Gas",
            "justering": "12000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE010",
            "marke": "Seat",
            "modell": "Arona 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "169900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 FR",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Style",
            "nybilspris": "172900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 115 Xcellence",
            "nybilspris": "184900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.0 TSI 95 Style",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.5 TSI 150 FR",
            "nybilspris": "195900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 95 Style",
            "nybilspris": "212900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Arona 1.6 TDI 95 Xcellence",
            "nybilspris": "201900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.0 TSI 115 Style",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO 4Drive DSG7 FR",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 4Drive Style",
            "nybilspris": "262900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 4Drive Xcellence",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO DSG7 Style",
            "nybilspris": "253900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO FR",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.5 TSI 150 EVO Xcellence",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 1.6 TDI 115 Style",
            "nybilspris": "247900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 150 FR",
            "nybilspris": "297900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TDI 190 4Drive DSG7 FR",
            "nybilspris": "337900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ateca 2.0 TSI 190 4Drive DSG7 FR",
            "nybilspris": "309900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Cupra Ateca 2.0 TSI 300 4Drive DSG7 Cupra",
            "nybilspris": "409900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 MPI 80 Style",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE032",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 FR, miljöbil",
            "nybilspris": "189900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE033",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TGI 90 Style, miljöbil",
            "nybilspris": "178900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 FR",
            "nybilspris": "165900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 Style DSG",
            "nybilspris": "169900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 115 Xcellence",
            "nybilspris": "165900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 FR",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 Style",
            "nybilspris": "149900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Ibiza 1.0 TSI 95 Xcellence",
            "nybilspris": "159900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 Ecomotive 115 DSG7 Style",
            "nybilspris": "196900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 FR",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 FR Edition",
            "nybilspris": "205900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.0 TSI 115 Style",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE036",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "224900",
            "bransletyp": "Gas",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE036",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "237900",
            "bransletyp": "Gas",
            "justering": "26000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE036",
            "marke": "Seat",
            "modell": "Leon 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "189900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR",
            "nybilspris": "217900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 130 Style",
            "nybilspris": "188900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR",
            "nybilspris": "228900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR DSG",
            "nybilspris": "250900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "215900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 1.6 TDI 115 Style",
            "nybilspris": "197900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR",
            "nybilspris": "248900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 150 FR Edition",
            "nybilspris": "235900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 184 DSG7 FR",
            "nybilspris": "276900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TDI 184 DSG7 FR Edition",
            "nybilspris": "263900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI 290 DSG7 Cupra",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI BZ 190 DSG7 FR",
            "nybilspris": "265900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon 2.0 TSI BZ 190 DSG7 FR Edition",
            "nybilspris": "252900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 Ecomotive 115 DSG7 Style",
            "nybilspris": "204900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.0 TSI 115 Style",
            "nybilspris": "182900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE053",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR, miljöbil",
            "nybilspris": "232900",
            "bransletyp": "Gas",
            "justering": "35000"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE053",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 FR Edition, miljöbil",
            "nybilspris": "251900",
            "bransletyp": "Gas",
            "justering": "28500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SE053",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TGI 130 Style, miljöbil",
            "nybilspris": "217900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR",
            "nybilspris": "225900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 130 FR Edition",
            "nybilspris": "214900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI Evo 130 Style",
            "nybilspris": "196900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR",
            "nybilspris": "236900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.5 TSI EVO 150 FR Edition",
            "nybilspris": "225900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 4Drive X-Perience",
            "nybilspris": "239900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 4Drive X-Perience Swedish Edition",
            "nybilspris": "229900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 1.6 TDI 115 Style",
            "nybilspris": "205900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 DSG7 4Drive FR",
            "nybilspris": "276900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 DSG7 4Drive FR Edition",
            "nybilspris": "265900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR",
            "nybilspris": "256900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TDI 150 FR Edition",
            "nybilspris": "245900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 4Drive X-Perience",
            "nybilspris": "279900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 190 DSG7 4Drive X-Perience Swedish Edition",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI 300 4Drive DSG7 Cupra",
            "nybilspris": "337900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI BZ 190 DSG7 FR",
            "nybilspris": "273900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Leon ST 2.0 TSI BZ 190 DSG7 FR Edition",
            "nybilspris": "262900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 1.5 TSI 150 Style",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 150 DSG7 4Drive Style",
            "nybilspris": "324900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 150 Style",
            "nybilspris": "284900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 190 DSG7 4Drive Xcellence",
            "nybilspris": "364900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TDI 190 DSG7 4Drive Xcellence Business Edition",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SE078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Seat",
            "modell": "Tarraco 2.0 TSI 190 DSG7 4Drive Xcellence",
            "nybilspris": "349900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}