export const skoda = {
    "resultCount": 163,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19SK146",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK146",
            "marke": "Skoda",
            "modell": "CITIGOe  iV BEV, Miljöbil",
            "nybilspris": "268400",
            "bransletyp": "El",
            "justering": "-133100"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Ambition TSI 110 Hk",
            "nybilspris": "153000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Ambition TSI 95 Hk",
            "nybilspris": "146500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Combi Ambition TSI 110 Hk",
            "nybilspris": "156900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Combi Ambition TSI 95 Hk",
            "nybilspris": "150400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Combi ScoutLine TSI 110 Hk",
            "nybilspris": "186300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Combi ScoutLine TSI 95 Hk",
            "nybilspris": "179800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Combi Style TSI 110 Hk",
            "nybilspris": "169600",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Combi Style TSI 95 Hk",
            "nybilspris": "163100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Monte Carlo TSI 110 Hk",
            "nybilspris": "177200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Monte Carlo TSI 95 Hk",
            "nybilspris": "170700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Style TSI 110 Hk",
            "nybilspris": "165700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Fabia Style TSI 95 Hk",
            "nybilspris": "159200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK147",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAMIQ AMBITION 1,6 115 DSG",
            "nybilspris": "261700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK148",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAMIQ AMBITION 1.0 115",
            "nybilspris": "215400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK149",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAMIQ AMBITION 1.5 150",
            "nybilspris": "234400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK150",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAMIQ STYLE 1.0 115",
            "nybilspris": "233900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK151",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAMIQ STYLE 1.5 150",
            "nybilspris": "253000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK152",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAMIQ STYLE 1.6 115 DSG",
            "nybilspris": "280200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Ambition TDI 115",
            "nybilspris": "244600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Ambition TDI 150",
            "nybilspris": "265500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Ambition TDI 150 4X4",
            "nybilspris": "283500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Ambition TDI 190 DSG 4X4",
            "nybilspris": "313500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Ambition TSI 115",
            "nybilspris": "220500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK153",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAROQ LIFE EDITION TSI 115",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Scout TDI 150 4X4",
            "nybilspris": "321000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Scout TDI 190 DSG 4X4",
            "nybilspris": "351900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Scout TSI 150 DSG 4X4",
            "nybilspris": "313800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq SportLine TDI 190 DSG 4X4",
            "nybilspris": "348000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq SportLine TSI 150",
            "nybilspris": "275300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq SportLine TSI 190 DSG 4X4",
            "nybilspris": "325800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK154",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KAROQ STYLE ADVENTURE EDITION TDI 150 DSG 4X4",
            "nybilspris": "334900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TDI 115",
            "nybilspris": "261800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TDI 150",
            "nybilspris": "282800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TDI 150 4X4",
            "nybilspris": "300800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TDI 190 DSG 4X4",
            "nybilspris": "330700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TSI 115",
            "nybilspris": "237500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TSI 150",
            "nybilspris": "262500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Karoq Style TSI 150 DSG 4X4",
            "nybilspris": "298300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Ambition TDI 150 Hk 4x4",
            "nybilspris": "298400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Ambition TDI 190 Hk DSG 4x4",
            "nybilspris": "321400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Ambition TSI 190 Hk DSG 4x4",
            "nybilspris": "302400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK155",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KODIAQ L&K ADVENTURE EDITION TDI 190 DSG 4X4",
            "nybilspris": "412900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK156",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "KODIAQ L&K ADVENTURE EDITION TSI 190 DSG 4X4",
            "nybilspris": "391400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq L&K TDI 190 Hk DSG 4X4",
            "nybilspris": "395500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq L&K TSI 190 Hk DSG 4X4",
            "nybilspris": "376500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq RS TDI 240 Hk DSG 4X4",
            "nybilspris": "440400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Scout Business Adventure Edition TDI 190 DSG 4x4",
            "nybilspris": "360000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Scout Business Adventure Edition TSI 190 DSG 4x4",
            "nybilspris": "341000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Scout TDI 150 Hk 4x4",
            "nybilspris": "339300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Scout TDI 190 Hk DSG 4x4",
            "nybilspris": "362300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Scout TSI 190 Hk DSG 4x4",
            "nybilspris": "343300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq SportLine Business Adventure Edition TDI 190 DSG 4x4",
            "nybilspris": "360000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq SportLine Business Adventure Edition TSI 190 DSG 4x4",
            "nybilspris": "341000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq SportLine TDI 190 Hk DSG 4x4",
            "nybilspris": "362400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq SportLine TSI 190 Hk DSG 4x4",
            "nybilspris": "343400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Style Business Adventure Edition TDI 150 4x4",
            "nybilspris": "312100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Style Business Adventure Edition TDI 190 DSG 4x4",
            "nybilspris": "335100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Style Business Adventure Edition TSI 190 DSG 4x4",
            "nybilspris": "316100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Style TDI 150 Hk 4x4",
            "nybilspris": "314400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Style TDI 190 Hk DSG 4x4",
            "nybilspris": "337400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Kodiaq Style TSI 190 Hk DSG 4x4",
            "nybilspris": "318400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Ambition TDI 115 Hk",
            "nybilspris": "229600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Ambition TDI 150 Hk",
            "nybilspris": "239500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Ambition TSI 115 Hk",
            "nybilspris": "206700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Ambition TSI ACT 150 Hk",
            "nybilspris": "227300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Ambition TDI 115 Hk",
            "nybilspris": "234100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Ambition TDI 150 Hk",
            "nybilspris": "244000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Ambition TDI 150 Hk DSG 4x4",
            "nybilspris": "265500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Ambition TSI 115 Hk",
            "nybilspris": "211300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK059",
            "marke": "Skoda",
            "modell": "Octavia Combi Ambition TSI 130 Hk G-TEC, miljöbil",
            "nybilspris": "245300",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Ambition TSI ACT 150 Hk",
            "nybilspris": "231800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi RS Business Sport Edition TDI 184 Hk DSG 4x4",
            "nybilspris": "289900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi RS Business Sport Edition TSI 245 Hk",
            "nybilspris": "295900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi RS TDI 184 Hk DSG",
            "nybilspris": "309200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi RS TDI 184 Hk DSG 4x4",
            "nybilspris": "316200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi RS TSI 245 Hk",
            "nybilspris": "310200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Scout Adventure Edition TDI 150 DSG 4X4",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Scout Adventure Edition TDI 184 DSG 4X4",
            "nybilspris": "291000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Scout Adventure Edition TSI 190 DSG 4X4",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Scout TDI 150 Hk DSG 4x4",
            "nybilspris": "290000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Scout TDI 184 Hk DSG 4x4",
            "nybilspris": "301100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Scout TSI 190 Hk DSG 4x4",
            "nybilspris": "286300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK157",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK079",
            "marke": "Skoda",
            "modell": "OCTAVIA COMBI STYLE ADVENTURE EDITION G-TEC TGI 130 CNG, miljöbil",
            "nybilspris": "259900",
            "bransletyp": "Gas",
            "justering": "8900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style Business Sport Edition TSI 150 Hk DSG",
            "nybilspris": "249900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style Business Sport Edition TSI 190 Hk DSG",
            "nybilspris": "259900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TDI 115 Hk",
            "nybilspris": "249000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TDI 150 Hk",
            "nybilspris": "258900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TDI 150 Hk DSG 4x4",
            "nybilspris": "280400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TDI 184 Hk DSG 4x4",
            "nybilspris": "293900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TSI 115 Hk",
            "nybilspris": "226200",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK079",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TSI 130 Hk G-TEC, miljöbil",
            "nybilspris": "260200",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TSI 190 Hk DSG",
            "nybilspris": "272100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TSI 190 Hk DSG 4x4",
            "nybilspris": "279100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Combi Style TSI ACT 150 Hk",
            "nybilspris": "246700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK084",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia RS Business Edition TDI 184 Hk DSG 4x4",
            "nybilspris": "287000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK085",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia RS Business Edition TSI 245 Hk",
            "nybilspris": "293000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK086",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia RS TDI 184 Hk DSG",
            "nybilspris": "306200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK087",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia RS TDI 184 Hk DSG 4x4",
            "nybilspris": "313200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK088",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia RS TSI 245 Hk",
            "nybilspris": "307300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK089",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Style TDI 115 Hk",
            "nybilspris": "244700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK090",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Style TDI 150 Hk",
            "nybilspris": "254600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK091",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Style TSI 115 Hk",
            "nybilspris": "221900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK092",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Style TSI 190 Hk DSG",
            "nybilspris": "267800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK093",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Octavia Style TSI ACT 150 Hk",
            "nybilspris": "242400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK142",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Scala Ambition TSI 115",
            "nybilspris": "200400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK143",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Scala Ambition TSI 150",
            "nybilspris": "218800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK144",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Scala Style TSI 115",
            "nybilspris": "215400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK145",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Scala Style TSI 150",
            "nybilspris": "233800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK094",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Ambition TDI 150 Hk",
            "nybilspris": "284800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK095",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Ambition TDI 150 Hk 4x4",
            "nybilspris": "291800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK096",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Ambition TDI 190 Hk DSG",
            "nybilspris": "313800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK097",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Ambition TDI 190 Hk DSG 4x4",
            "nybilspris": "320800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK098",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Ambition TSI 150 Hk",
            "nybilspris": "281500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK099",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Ambition TDI 150 Hk",
            "nybilspris": "293800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK100",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Ambition TDI 150 Hk 4x4",
            "nybilspris": "300800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK101",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Ambition TDI 190 Hk DSG",
            "nybilspris": "322800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK102",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Ambition TDI 190 Hk DSG 4x4",
            "nybilspris": "329800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK103",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Ambition TSI 150 Hk",
            "nybilspris": "290500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK104",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi L&K Business Adventure Edition TDI 190 DSG 4X4",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK105",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi L&K Business Adventure Edition TSI 272 DSG 4X4",
            "nybilspris": "374900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK158",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK121",
            "marke": "Skoda",
            "modell": "SUPERB COMBI L&K iV 1.4 TSI PHEV, Miljöbil",
            "nybilspris": "455200",
            "bransletyp": "Laddhybrid",
            "justering": "62800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK106",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi L&K TDI 190 Hk DSG",
            "nybilspris": "354900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK107",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi L&K TDI 190 Hk DSG 4x4",
            "nybilspris": "361900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK108",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi L&K TSI 272 Hk DSG 4x4",
            "nybilspris": "391400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK109",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Sportline Business Adventure Edition TDI 190 DSG 4X4",
            "nybilspris": "335900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK110",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Sportline Business Adventure Edition TSI 272 DSG 4X4",
            "nybilspris": "366900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK159",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK121",
            "marke": "Skoda",
            "modell": "SUPERB COMBI SPORTLINE iV 1.4 TSI PHEV, miljöbil",
            "nybilspris": "482100",
            "bransletyp": "Laddhybrid",
            "justering": "57300"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK111",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi SportLine TDI 190 Hk DSG",
            "nybilspris": "364100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK112",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi SportLine TDI 190 Hk DSG 4x4",
            "nybilspris": "371100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK113",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi SportLine TSI 272 Hk DSG 4x4",
            "nybilspris": "398600",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK114",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style Business Adventure Edition 2,0 TDI 190 Hk DSG 4x4",
            "nybilspris": "319900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK115",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style Business Adventure Edition TDI 150 DSG",
            "nybilspris": "301800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK116",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style Business Adventure Edition TSI 150 DSG",
            "nybilspris": "299900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK160",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK121",
            "marke": "Skoda",
            "modell": "SUPERB COMBI STYLE iV 1.4 TSI PHEV, miljöbil",
            "nybilspris": "429500",
            "bransletyp": "Laddhybrid",
            "justering": "43200"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK117",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style TDI 150 Hk",
            "nybilspris": "303600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK118",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style TDI 150 Hk 4x4",
            "nybilspris": "310600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK119",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style TDI 190 Hk DSG",
            "nybilspris": "332600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK120",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style TDI 190 Hk DSG 4x4",
            "nybilspris": "336700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK121",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style TSI 150 Hk",
            "nybilspris": "300300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK122",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Combi Style TSI 272 Hk DSG 4x4",
            "nybilspris": "369100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK123",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb L&K Business Adventure Edition TDI 190 DSG 4X4",
            "nybilspris": "332000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK124",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb L&K Business Adventure Edition TSI 272 DSG 4X4",
            "nybilspris": "365900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK161",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK140",
            "marke": "Skoda",
            "modell": "SUPERB L&K iV 1.4 TSI PHEV, Miljöbil",
            "nybilspris": "445800",
            "bransletyp": "Laddhybrid",
            "justering": "62400"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK125",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb L&K TDI 190 Hk DSG",
            "nybilspris": "345600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK126",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb L&K TDI 190 Hk DSG 4x4",
            "nybilspris": "352600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK127",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb L&K TSI 272 Hk DSG 4x4",
            "nybilspris": "382100",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK128",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Sportline Business Adventure Edition TDI 190 DSG 4X4",
            "nybilspris": "326900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK129",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Sportline Business Adventure Edition TSI 272 DSG 4X4",
            "nybilspris": "357900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK162",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK140",
            "marke": "Skoda",
            "modell": "SUPERB SPORTLINE iV 1.4 TSI PHEV, miljöbil",
            "nybilspris": "472700",
            "bransletyp": "Laddhybrid",
            "justering": "56900"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK130",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb SportLine TDI 190 Hk DSG",
            "nybilspris": "355100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK131",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb SportLine TDI 190 Hk DSG 4x4",
            "nybilspris": "362100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK132",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb SportLine TSI 272 Hk DSG 4x4",
            "nybilspris": "389600",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK133",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style Business Adventure Edition TDI 150 DSG",
            "nybilspris": "292800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK134",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style Business Adventure Edition TDI 190 Hk DSG 4x4",
            "nybilspris": "313800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK135",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style Business Adventure Edition TSI 150 DSG",
            "nybilspris": "290900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK163",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19SK140",
            "marke": "Skoda",
            "modell": "SUPERB STYLE iV 1.4 TSI PHEV,miljöbil",
            "nybilspris": "420100",
            "bransletyp": "Laddhybrid",
            "justering": "42800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK136",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style TDI 150 Hk",
            "nybilspris": "294600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK137",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style TDI 150 Hk 4x4",
            "nybilspris": "301600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK138",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style TDI 190 Hk DSG",
            "nybilspris": "323600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK139",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style TDI 190 Hk DSG 4x4",
            "nybilspris": "330600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK140",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style TSI 150 Hk",
            "nybilspris": "291300",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19SK141",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Skoda",
            "modell": "Superb Style TSI 272 Hk DSG 4x4",
            "nybilspris": "360100",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}