export const volkswagen = {
    "resultCount": 203,
    "offset": 0,
    "limit": 500,
    "results": [
        {
            "fordonstyp": "Personbil",
            "kod": "19VW129",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GTR TSI 272 DSG7 4M",
            "nybilspris": "519900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW130",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GTR TSI 272 DSG7 4M Executive R Edt",
            "nybilspris": "452900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW163",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GTS TDI 240 DSG7 4M Executive R Edt",
            "nybilspris": "465900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW001",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GT TDI 190 DSG7 4M",
            "nybilspris": "414900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW002",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GT TDI 190 DSG7 4M R-line",
            "nybilspris": "424900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW161",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GT TDI 190 DSG7 4M R-line - MY 2020",
            "nybilspris": "444900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW003",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GT TDI 190 Executive R Edt",
            "nybilspris": "364900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW162",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Arteon GT TDI 190 Executive R Edt - MY 2020",
            "nybilspris": "409900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW131",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY ALLTR eu6 tdi 122hk 4m",
            "nybilspris": "318400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW132",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY ALLTR eu6 tdi 150hk dsg/4m",
            "nybilspris": "350800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW004",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY COMFORTLI eu6 tdi 102hk dsg",
            "nybilspris": "274600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW005",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY COMFORTLI eu6 tdi 150hk dsg",
            "nybilspris": "291000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW006",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY COMFORTLI eu6 tdi150hk dsg/4m",
            "nybilspris": "320000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW007",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW008",
            "marke": "Volkswagen",
            "modell": "CADDY COMFORTLI eu6 tgi 110hk, miljöbil",
            "nybilspris": "259000",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW008",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY COMFORTLI eu6 tsi 130hk",
            "nybilspris": "234500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW014",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI COMFO eu6 tdi 102hk dsg",
            "nybilspris": "298100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW015",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI COMFO eu6 tdi 150hk dsg",
            "nybilspris": "314700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW017",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI COMFO eu6tdi150hk dsg/4m",
            "nybilspris": "341200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW016",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW015",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI COMFO eu6 tgi 110hk, miljöbil",
            "nybilspris": "295900",
            "bransletyp": "Gas",
            "justering": "-51500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW018",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI HIGHL eu6 tdi150hk dsg/4m",
            "nybilspris": "371900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW019",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI HIGHL eu6 tsi 125hk dsg",
            "nybilspris": "302900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW020",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI TREND eu6 tdi 102hk",
            "nybilspris": "262000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW021",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI TREND eu6 tdi 122hk 4m",
            "nybilspris": "292000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW022",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW023",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI TREND eu6 tgi 110hk, miljöbil",
            "nybilspris": "272900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW023",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI TREND eu6 tsi 130hk",
            "nybilspris": "242900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW135",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDYMAXI TRENDLINE eu6 tsi 102",
            "nybilspris": "241500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW009",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tdi 102hk",
            "nybilspris": "238500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW010",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tdi 122hk 4m",
            "nybilspris": "264000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW011",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tdi 75hk",
            "nybilspris": "217000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW012",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW013",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tgi 110hk, miljöbil",
            "nybilspris": "241000",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW133",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tsi 102hk",
            "nybilspris": "215000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW013",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tsi 130hk",
            "nybilspris": "217000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW134",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "CADDY TRENDLINE eu6 tsi 84hk",
            "nybilspris": "208000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW024",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf Alltrack TDI 184",
            "nybilspris": "325900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW136",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf Alltrack TDI 184 Limited Edt",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW025",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW046",
            "marke": "Volkswagen",
            "modell": "Golf e-Golf, miljöbil",
            "nybilspris": "418900",
            "bransletyp": "El",
            "justering": "15200"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW027",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf GTD TDI 184 DSG7",
            "nybilspris": "329900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW028",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf GTI 245",
            "nybilspris": "319900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW165",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf GTI TCR",
            "nybilspris": "449900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW026",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf GT TSI 150",
            "nybilspris": "251900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW164",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf GT TSI 150 R-line Edt",
            "nybilspris": "244900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW029",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf R 300 DSG7",
            "nybilspris": "429900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW030",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC GT TDI 150",
            "nybilspris": "278000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW166",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC GT TDI 150 DSG",
            "nybilspris": "305500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW031",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC GT TSI 150",
            "nybilspris": "259400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW137",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC GT TSI 150 R-line Edt",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW032",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC R 300 DSG7",
            "nybilspris": "437400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW033",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC TDI 115",
            "nybilspris": "243500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW167",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC TDI 115 Edt",
            "nybilspris": "232400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW034",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC TDI 150 DSG 4M",
            "nybilspris": "271400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW138",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC TDI 150 DSG 4M R-line Edt",
            "nybilspris": "279900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW035",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW036",
            "marke": "Volkswagen",
            "modell": "Golf SC TGI 110, miljöbil",
            "nybilspris": "251500",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW139",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW037",
            "marke": "Volkswagen",
            "modell": "Golf SC TGI 130, miljöbil",
            "nybilspris": "277400",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW168",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW037",
            "marke": "Volkswagen",
            "modell": "Golf SC TGI 130 DSG7, miljöbil",
            "nybilspris": "297900",
            "bransletyp": "Gas",
            "justering": "15500"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW036",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC TSI 115",
            "nybilspris": "219400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW037",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf SC TSI 130",
            "nybilspris": "247400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW038",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf Sportsvan GT TSI 150 DSG7",
            "nybilspris": "280900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW039",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf Sportsvan TDI 115",
            "nybilspris": "249500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW040",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf Sportsvan TSI 115",
            "nybilspris": "225400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW041",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf Sportsvan TSI 130",
            "nybilspris": "253400",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW042",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TDI 115",
            "nybilspris": "236000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW169",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TDI 115 Edt",
            "nybilspris": "224900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW043",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TDI 150 DSG 4M",
            "nybilspris": "263900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW044",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TDI 150 GT DSG 4M",
            "nybilspris": "292900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW045",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW046",
            "marke": "Volkswagen",
            "modell": "Golf TGI 110, miljöbil",
            "nybilspris": "244000",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW140",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW047",
            "marke": "Volkswagen",
            "modell": "Golf TGI 130, miljöbil",
            "nybilspris": "269900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW046",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TSI 115",
            "nybilspris": "211900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW170",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TSI 115 Edt",
            "nybilspris": "213900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW047",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Golf TSI 130",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW174",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) Alltrack GTS TDI 240 DSG7 4M",
            "nybilspris": "439900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW171",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) Alltrack GT TDI 190 DSG7 4M",
            "nybilspris": "363700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW172",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) Alltrack GT TDI 190 DSG7 4M Edition",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW173",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) Alltrack GT TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "363700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW175",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) Alltrack TSI 272 GTS",
            "nybilspris": "439900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW176",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW187",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) GTE, miljöbil",
            "nybilspris": "448500",
            "bransletyp": "Laddhybrid",
            "justering": "5800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW178",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW185",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC GTE, miljöbil",
            "nybilspris": "458500",
            "bransletyp": "Laddhybrid",
            "justering": "5800"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW179",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC GTS TDI 240 DSG7 4M",
            "nybilspris": "424900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW177",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC GT TSI 190 DSG7",
            "nybilspris": "348700",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW180",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC TDI 150 DSG7",
            "nybilspris": "339800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW181",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC TDI 190 DSG7",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW182",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC TDI 190 DSG7 4M",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW183",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW184",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC TDI 190 DSG7 Executive Edt",
            "nybilspris": "348700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW185",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) SC TSI 150 Edt",
            "nybilspris": "289900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW186",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) TDI 150 DSG7",
            "nybilspris": "329800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW187",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat (Nya) TSI 150",
            "nybilspris": "309900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW142",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat Alltrack GTS TDI 240 DSG7 4M",
            "nybilspris": "439900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW143",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat Alltrack GTS TDI 240 DSG7 4M Executive Edt",
            "nybilspris": "365000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW048",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat Alltrack GT TDI 190 DSG7 4M",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW049",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat Alltrack GT TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW141",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat Alltrack GT TSI 272 DSG7 4M",
            "nybilspris": "424900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW052",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW062",
            "marke": "Volkswagen",
            "modell": "Passat GTE, miljöbil",
            "nybilspris": "433500",
            "bransletyp": "Laddhybrid",
            "justering": "30600"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW050",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat GT TDI 190 DSG7",
            "nybilspris": "324100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW051",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat GT TDI 190 DSG7 4M",
            "nybilspris": "331000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW144",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat GT TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "331000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW145",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat GT TDI 190 DSG7 Executive Edt",
            "nybilspris": "324100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW059",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW061",
            "marke": "Volkswagen",
            "modell": "Passat SC GTE, miljöbil",
            "nybilspris": "443500",
            "bransletyp": "Laddhybrid",
            "justering": "30600"
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW146",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GTR TSI 272 DSG7 4M",
            "nybilspris": "469900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW147",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GTS TDI 240 DSG7 4M Executive Edt",
            "nybilspris": "351000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW053",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GT TDI 150 DSG7",
            "nybilspris": "334100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW054",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GT TDI 150 DSG7 Executive Edt",
            "nybilspris": "334100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW055",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GT TDI 190 DSG7",
            "nybilspris": "334100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW056",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GT TDI 190 DSG7 4M",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW057",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GT TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW058",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC GT TDI 190 DSG7 Executive Edt",
            "nybilspris": "334100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW060",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC TDI 150",
            "nybilspris": "316000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW061",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat SC TSI 150",
            "nybilspris": "269900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW062",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Passat TSI 150 EVO",
            "nybilspris": "273900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW064",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Polo GTI 200",
            "nybilspris": "239900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW063",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Polo GT TSI 150 EVO DSG7",
            "nybilspris": "219900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW065",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Polo TDI 95",
            "nybilspris": "204900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW066",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW067",
            "marke": "Volkswagen",
            "modell": "Polo TGI 90, miljöbil",
            "nybilspris": "188900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW067",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Polo TSI 95",
            "nybilspris": "164900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW068",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan GT TDI 177 DSG6 4M",
            "nybilspris": "437900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW069",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan GT TDI 177 DSG6 4M Premium Edt",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW148",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan GT TDI 177 DSG6 4M Premium Edt - Paketering 2019",
            "nybilspris": "399900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW188",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan GT TDI 177 DSG7 4M - MY 2020",
            "nybilspris": "472900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW189",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan GT TDI 177 DSG7 4M Premium Edt - MY 2020",
            "nybilspris": "412900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW149",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan GT TDI 184 DSG6 4M Premium Edt",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW150",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan TDI 150",
            "nybilspris": "359900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW070",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan TDI 150 Premium",
            "nybilspris": "329100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW190",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan TDI 150 Premium - MY 2020",
            "nybilspris": "361700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW071",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan TSI 150 DSG6",
            "nybilspris": "341000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW191",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Sharan TSI 150 DSG6 - MY 2020",
            "nybilspris": "372900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW078",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CALIFORNIA 150hk tdi",
            "nybilspris": "564300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW079",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CALIFORNIA 150hk tdi 4m",
            "nybilspris": "596700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW080",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CALIFORNIA 199hk tdi dsg",
            "nybilspris": "634400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW077",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CALIFORNIA  199hk tdi dsg/4m",
            "nybilspris": "638800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW081",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 102hk tdi 300",
            "nybilspris": "463500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW082",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 102hk tdi 340",
            "nybilspris": "451200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW083",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 150hk tdi 300",
            "nybilspris": "488400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW084",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 150hk tdi 340",
            "nybilspris": "476100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW085",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 150hk tdi 4m 300",
            "nybilspris": "523600",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW086",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 150hk tdi 4m 340",
            "nybilspris": "510400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW089",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 199hk tdi dsg/4m 300",
            "nybilspris": "581200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW090",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 199hk tdi dsg/4m 340",
            "nybilspris": "568800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW087",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 199hk tdi dsg 300",
            "nybilspris": "551500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW088",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE cl 199hk tdi dsg 340",
            "nybilspris": "539000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW091",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE tl 102hk tdi 340",
            "nybilspris": "424800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW092",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE tl 150hk tdi 340",
            "nybilspris": "450000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW093",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE tl 150hk tdi 4m 340",
            "nybilspris": "482900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW095",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE tl 199hk tdi dsg/4m 340",
            "nybilspris": "553900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW094",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 CARAVELLE tl 199hk tdi dsg  340",
            "nybilspris": "518000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW096",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl 150hk tdi",
            "nybilspris": "421800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW097",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl 150hk tdi 4m",
            "nybilspris": "453400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW098",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl 199hk tdi dsg",
            "nybilspris": "488200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW099",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl 199hk tdi dsg/4m",
            "nybilspris": "518100",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW100",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl lå 150hk tdi",
            "nybilspris": "464900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW101",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl lå 150hk tdi 4m",
            "nybilspris": "500200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW102",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl lå 199hk tdi dsg",
            "nybilspris": "521800",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW103",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN cl lå 199hk tdi dsg/4m",
            "nybilspris": "557500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW104",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN hl 150hk tdi",
            "nybilspris": "475200",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW105",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN hl 150hk tdi 4m",
            "nybilspris": "499500",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW106",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN hl 199hk tdi dsg",
            "nybilspris": "548900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW107",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T6 MULTIVAN hl 199hk tdi dsg/4m",
            "nybilspris": "565300",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW192",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Cross GT TSI 115",
            "nybilspris": "223900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW193",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Cross TDI 95",
            "nybilspris": "234900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW194",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Cross TSI 95",
            "nybilspris": "199900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW110",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace GTS TDI 240 DSG7 4M",
            "nybilspris": "454000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW111",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace GTS Zeiss Edt",
            "nybilspris": "509900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW108",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace GT TDI 190 DSG7 4M",
            "nybilspris": "399900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW151",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace GT TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "393700",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW109",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace GT TSI 220 DSG7 4M",
            "nybilspris": "424000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW112",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace TSI 180 DSG7 4M",
            "nybilspris": "352000",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW152",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace TSI 190 DSG7 4M",
            "nybilspris": "369900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW153",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace TSI 190 DSG7 4M Executive Edt",
            "nybilspris": "349900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW198",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan Allspace TSI 190 DSG7 4M Executive Edt (MY 2020)",
            "nybilspris": "380800",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW199",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan GTS TDI 240 DSG7 4M",
            "nybilspris": "429900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW200",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan GTS TDI 240 DSG7 4M Executive Edt",
            "nybilspris": "429900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW113",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan GT TDI 190 DSG7 4M",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW114",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan GT TDI 190 DSG7 4M Executive Edt",
            "nybilspris": "341000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW115",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan GT TSI 220 DSG7 4M",
            "nybilspris": "387500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW154",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan GT TSI 230 DSG7 4M",
            "nybilspris": "394900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW116",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan TDI 150 DSG7 4M Limited Edt",
            "nybilspris": "314900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW117",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan TSI 180 DSG7 4M",
            "nybilspris": "290500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW155",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan TSI 190 DSG7 4M",
            "nybilspris": "344900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW156",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Tiguan TSI 190 DSG7 4M Executive Edt",
            "nybilspris": "304900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW118",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touareg V6 TDI 286 4M",
            "nybilspris": "589900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW157",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touareg V6 TDI 286 4M Edition X",
            "nybilspris": "649900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW158",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touareg V6 TSI 340",
            "nybilspris": "599900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW201",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touareg V6 TSI 340 4M Edition X",
            "nybilspris": "649900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW119",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran GT TDI 190 DSG7",
            "nybilspris": "348000",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW120",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TDI 115",
            "nybilspris": "284900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW202",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TDI 115 DSG7",
            "nybilspris": "305400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW121",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TDI 150",
            "nybilspris": "303900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW203",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TDI 150 DSG7",
            "nybilspris": "330400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW159",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TDI 150 DSG7 R-line Edt",
            "nybilspris": "294900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW122",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TSI 110",
            "nybilspris": "213900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW160",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TSI 115",
            "nybilspris": "264900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW123",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TSI 150",
            "nybilspris": "272900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW124",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "Touran TSI 150 DSG7 R-line Edt",
            "nybilspris": "272900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW072",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc GT TDI 190 DSG7 4M",
            "nybilspris": "326900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW073",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc GT TSI 190 DSG7 4M",
            "nybilspris": "306900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW195",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc R",
            "nybilspris": "409900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW074",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc TDI 150 4M",
            "nybilspris": "268900",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW196",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc TDI 150 DSG 4M",
            "nybilspris": "295400",
            "bransletyp": "Diesel",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW075",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc TSI 115",
            "nybilspris": "213900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW197",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc TSI 150",
            "nybilspris": "252500",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW076",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "T-Roc TSI 190 DSG7 4M",
            "nybilspris": "279900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW126",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW128",
            "marke": "Volkswagen",
            "modell": "up! eco up!, miljöbil",
            "nybilspris": "171900",
            "bransletyp": "Gas",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW125",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "19VW128",
            "marke": "Volkswagen",
            "modell": "up! e-up!, miljöbil",
            "nybilspris": "284900",
            "bransletyp": "El",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW127",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "up! GTI",
            "nybilspris": "174900",
            "bransletyp": "Bensin",
            "justering": ""
        },
        {
            "fordonstyp": "Personbil",
            "kod": "19VW128",
            "filskapaddatum": "2019-11-04 00:00",
            "tillverkningsar": "2019",
            "kodforjamforbarmodell": "",
            "marke": "Volkswagen",
            "modell": "up! High Up! 1,0 MPI",
            "nybilspris": "139900",
            "bransletyp": "Bensin",
            "justering": ""
        }
    ]
}